### ISSUE TITLE
Input Images

### ISSUE THREAD

**Issue by DexHunter** [lllyasviel/style2paints#1]
I wonder have you tried that first decolorize a anime image then use your method to color it again and see what the result?

**Comment by DexHunter** [comment]
[這是](http://stellarcoder.com/surf/anime_test/)我用pix2pix訓練12個epoch的結果，可能是我input沒有處理非常好，所以感覺結果不是很好。看了你們的論文感覺是個新的方向

**Comment by lllyasviel** [comment]
并没有试过 但是直觉上应该不会有显著的改善 点信号和全局信号是冲突的

**Comment by lllyasviel** [comment]
你们的线稿问题很大 建议是用我的github里面的sketchKeras来搞线稿

**Comment by DexHunter** [comment]
對，因為是直接用opencv裡canny的。。
