### ISSUE TITLE
[Instruction] Run style2paints v3 offline

### ISSUE THREAD

**Issue by HynoR** [lllyasviel/style2paints#100]
Here is the instruction about how to install the offline code on Windows(x64) devices.
中文教程：http://c7.gg/fEPeq
### Instruction
Anaconda is a useful tool to contain python env. https://www.anaconda.com/
1.Download [python 3.6.7](https://www.python.org/downloads/release/python-367/) and install.
I.If you have installed other version,you need to uninstall it.
![pic](https://raw.githubusercontent.com/SNSLogty/style2paints_v3_launcher/master/4.png)
2.Open cmd and input
`pip install -r requirement_xxx.txt`
GPU(GTX 1060 6G or better):
https://raw.githubusercontent.com/SNSLogty/style2paints_v3_launcher/master/requirement_gpu.txt
CPU:(high compatibility)
https://raw.githubusercontent.com/SNSLogty/style2paints_v3_launcher/master/requirement_cpu.txt
![pic](https://raw.githubusercontent.com/SNSLogty/style2paints_v3_launcher/master/5.png)
3.Download [the source code](https://github.com/lllyasviel/style2paints/tree/master/V3) and [models](https://github.com/lllyasviel/style2paints/tree/master/V3#models)
Put the models into 'server' folder.
4.Run server.py
![pic](https://raw.githubusercontent.com/SNSLogty/style2paints_v3_launcher/master/6.png)
5.When you see "Listening to 0.0.0.0:port" , open "http://127.0.0.1:port/" in your web browser (use Chrome or Edge.Do NOT use firefox)
![pic](https://raw.githubusercontent.com/SNSLogty/style2paints_v3_launcher/master/1.png)
![pic](https://raw.githubusercontent.com/SNSLogty/style2paints_v3_launcher/master/2.png)

### _F&A_
**About error 403 Forbidden:** https://github.com/lllyasviel/style2paints/issues/84

you can download [server.py_corrected](https://raw.githubusercontent.com/SNSLogty/style2paints_v3_launcher/master/server.py) and replace the file.

**About V4 resources:**https://github.com/lllyasviel/style2paints/issues/87#issuecomment-441222893

You can get the latest news from our social account
 Twitter: https://twitter.com/IlIIlIIIllIllII
 Sina Weibo: https://www.weibo.com/STYLE2PAINTS
 Bilibili(not official):https://space.bilibili.com/4582779
 Youtube:https://www.youtube.com/channel/UCFEVJIaqRneO2Y3VpdIFI3w
**This Tutorial is not perfect at present.**

If you have too many unknown problems.
Try non-install pack (CPU)
https://mega.nz/#!x8lhQa6Q!EZb75h9f1VoWrLDiQj79GK5UVC0LM3G785wiChfzeJ0
you can find the instruction here
#71

**Comment by Ben76904** [comment]
I followed the instructions and they were great. But I keep getting "unable to connect". Here's a screenshot.
![server unable to con](https://user-images.githubusercontent.com/46573188/51515661-2efe3b00-1dda-11e9-836b-8dd0b1b33034.jpg)

**Comment by onsoho** [comment]
> I followed the instructions and they were great. But I keep getting "unable to connect". Here's a screenshot.
> ![server unable to con](https://user-images.githubusercontent.com/46573188/51515661-2efe3b00-1dda-11e9-836b-8dd0b1b33034.jpg)

127.0.0.1:80*

**Comment by SNSLogty** [comment]
@Ben76904 @onsoho Try 127.0.0.1:80

**Comment by Ben76904** [comment]
@SNSLogty I've tried that as well. I keep getting  "Access Denied". I think It's my proxy settings. Will try again. If it doesn't work, no problem. I'll wait for the server to come back online.
![server error](https://user-images.githubusercontent.com/46573188/51560676-d7e47e80-1e4a-11e9-9516-141bd275bf9b.jpg)

**Comment by CambaCambaCambaCambaCambaCamba** [comment]
I'm getting a white blank page, any ideas why?

**Comment by abdellbobo** [comment]
@Ben76904 try 0.0.0.0:80 and use Google Chrome.

**Comment by SNSLogty** [comment]
@CambaCambaCambaCambaCambaCamba 
> I'm getting a white blank page, any ideas why?
Use Chrome or Edge to open the page

**Comment by SNSLogty** [comment]
> @SNSLogty I've tried that as well. I keep getting "Access Denied". I think It's my proxy settings. Will try again. If it doesn't work, no problem. I'll wait for the server to come back online.
> ![server error](https://user-images.githubusercontent.com/46573188/51560676-d7e47e80-1e4a-11e9-9516-141bd275bf9b.jpg)

@Ben76904 
From issue https://github.com/lllyasviel/style2paints/issues/84
> Windows 10, this worked for me:
> In server.py change:
> `static_file("index.html", root='game/')`
> To:
> `static_file("index.html", root='./game')`

**Comment by Ben76904** [comment]
@SNSLogty Had to change one other line as well after following your instructions. Or else I get white blank page. It works now. Thank you so much! Here's the two lines. 

```
@route('/<filename:path>')
def send_static(filename):
    return static_file(filename, root='./game')


@route('/')
def send_static():
    return static_file("index.html", root='./game')
```

**Comment by LapoRighini** [comment]
![problem](https://user-images.githubusercontent.com/23381222/51800331-c83fae00-222d-11e9-8b21-389b78094a12.PNG)
After i "upload" the image the server crash, Can anyone help me? :c

**Comment by Ben76904** [comment]
For me, the offline version is slow. Uploading an image takes 30 seconds and to render a painting takes about 50 seconds. I did the CPU install. Is this normal?

**Comment by IKAR0S** [comment]
@SNSLogty, how can i integrate Danbooru2017 Dataset?

**Comment by Luke-lujunxian** [comment]
> For me, the offline version is slow. Uploading an image takes 30 seconds and to render a painting takes about 50 seconds. I did the CPU install. Is this normal?

I believe it is normal. But, taking 30s to "upload" sounds strange for local sever. Maybe some works are done during the upload process.

**Comment by Ben76904** [comment]
@Luke-lujunxian Good to know. Thanks!

**Comment by IKAR0S** [comment]
@stefnotch i also had the same problem and solved it by replacing server.py with [server.py_corrected](https://raw.githubusercontent.com/SNSLogty/style2paints_v3_launcher/master/server.py)

**Comment by stefnotch** [comment]
@IKAR0S I replaced mine with the corrected server.py, however the issue persisted.

**Comment by melocule** [comment]
It doesn't work for me.
![image](https://user-images.githubusercontent.com/33408946/52382433-43317180-2a43-11e9-8ecf-7833f0ef4f9c.png)

**Comment by SNSLogty** [comment]
@melocule 
Try non-install stable-pack
https://mega.nz/#!x8lhQa6Q!EZb75h9f1VoWrLDiQj79GK5UVC0LM3G785wiChfzeJ0
you can find the instruction here
#71

**Comment by shadowzach7** [comment]
Yeah I have seem to set everything up correctly and have a GPU compatible with tensorflow (gtx 1060) as other projects have worked, however whenever I run this I am able to get to the website and upload and image but then after the preparing bar fills my computer freezes up and blue screens giving my a driver power state failure. Any ideas?

**Comment by Datguypotato** [comment]
![image](https://user-images.githubusercontent.com/44816915/56866821-34bd7b00-69de-11e9-917d-300823fa8bab.png)

I am new to python it seems that I am missing a module
I can't find anything useful on google can somebody help me out?

**Comment by stefnotch** [comment]
https://raw.githubusercontent.com/SNSLogty/style2paints_v3_launcher/master/requirement_cpu.txt

`pip install -r requirement_cpu.txt`

**Comment by Datguypotato** [comment]
> [https://raw.githubusercontent.com/SNSLogty/style2paints_v3_launcher/master/requirement_cpu](https://raw.githubusercontent.com/SNSLogty/style2paints_v3_launcher/master/requirement_cpu.txt)

I get this error.
 ERROR: Could not find a version that satisfies the requirement tensorflow (from -r requirement_cpu.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for tensorflow (from -r requirement_cpu.txt (line 1))

**Comment by SNSLogty** [comment]
> > [https://raw.githubusercontent.com/SNSLogty/style2paints_v3_launcher/master/requirement_cpu](https://raw.githubusercontent.com/SNSLogty/style2paints_v3_launcher/master/requirement_cpu.txt)
> 
> I get this error.
> ERROR: Could not find a version that satisfies the requirement tensorflow (from -r requirement_cpu.txt (line 1)) (from versions: none)
> ERROR: No matching distribution found for tensorflow (from -r requirement_cpu.txt (line 1))

@Datguypotato 
Try this command first
`pip install tensorflow-1.10.0-cp36-cp36m-win_amd64.whl`
then install requirement_cpu.txt

**Comment by 852953573** [comment]
![screenshot20190616122100](https://user-images.githubusercontent.com/49689647/59559008-7dce9a80-9031-11e9-8607-b19353a0b39e.png)
我是不是漏了一步QAQ

**Comment by IKAR0S** [comment]
@852953573 try this [version](https://mega.nz/#!x8lhQa6Q!EZb75h9f1VoWrLDiQj79GK5UVC0LM3G785wiChfzeJ0)

**Comment by 852953573** [comment]
> @ 852953573试试这个[版本](https://mega.nz/#!x8lhQa6Q!EZb75h9f1VoWrLDiQj79GK5UVC0LM3G785wiChfzeJ0)

谢谢 

thank you

**Comment by exi3t** [comment]
> ![screenshot20190616122100](https://user-images.githubusercontent.com/49689647/59559008-7dce9a80-9031-11e9-8607-b19353a0b39e.png)
> 我是不是漏了一步QAQ

我跟你差不多问题,win7
![捕获](https://user-images.githubusercontent.com/35194938/62852554-4839eb00-bd1c-11e9-930c-55bf6d20fb4e.JPG)

**Comment by stefnotch** [comment]
@exi3t 
It looks like it can't find `baby.net`. Are you sure that you downloaded the [tensorflow models](https://github.com/lllyasviel/style2paints/tree/master/V3#models) and put them in the correct folder?

**Comment by exi3t** [comment]
> @exi3t
> It looks like it can't find `baby.net`. Are you sure that you downloaded the [tensorflow models](https://github.com/lllyasviel/style2paints/tree/master/V3#models) and put them in the correct folder?

thanx,I have already used the noinstall version and it works.

**Comment by Tomluk811** [comment]
Hi, I got problem when trying to start server. Any idea for fix?
![Przechwytywanie](https://user-images.githubusercontent.com/54036109/62880578-031eb480-bd2e-11e9-8b1b-6004cb625afc.PNG)

**Comment by stefnotch** [comment]
StackOverflow yields a bunch of results when searching for the error message `No module named '_pywrap_tensorflow_internal'`

Some of the top results are
- [TensorFlow on Windows: ImportError: No module named '_pywrap_tensorflow_internal' - StackOverflow](https://stackoverflow.com/questions/43751418/tensorflow-on-windows-importerror-no-module-named-pywrap-tensorflow-internal)
- [No Module Named '_pywrap_tensorflow_internal' - StackOverflow](https://stackoverflow.com/questions/44080677/no-module-named-pywrap-tensorflow-internal)

**Comment by edwinma0309** [comment]
![IMG_20190813_224726](https://user-images.githubusercontent.com/47510881/62951508-b36ae680-be1c-11e9-98ff-4599707c9bdb.jpg)
How can I solve this problem?

**Comment by SNSLogty** [comment]
@Tomluk811  You may use 32-bit version python,Try to install the 64-bit version.

**Comment by MuQQQQQ** [comment]
How can I stop the server?
I sucessfully installed s2p, but, although I closed the cmd, the page of  `127.0.0.1`  is still PaintsTranfer.

**Comment by LCYLYM** [comment]
> 如何停止服务器？
> 我已成功安装了s2p，但是，尽管我关闭了cmd，但其页面 `127.0.0.1` 仍然是PaintsTranfer。

那只是缓存

**Comment by MuQQQQQ** [comment]
> > 如何停止服务器？
> > 我已成功安装了s2p，但是，尽管我关闭了cmd，但其页面 `127.0.0.1` 仍然是PaintsTranfer。
> 
> 那只是缓存

kusa，谢谢orz

**Comment by mihaelkeelh** [comment]
guys i
how do you make the actual resolution in this application?
i have photo with 2000px but 
after I color it, the resolution is only at 1000 px how i can change the resolution ?

**Comment by MX-Qulin** [comment]
中文版已失效

**Comment by gceboh** [comment]
Thanks for providing the tutorial. 
Currently (in the year 2020), the [requirements.txt](https://raw.githubusercontent.com/SNSLogty/style2paints_v3_launcher/master/requirement_cpu.txt) is out of date. pip install will cause the following warning info:

> ERROR: tifffile 2020.6.3 has requirement numpy>=1.15.1, but you'll have numpy 1.
 is incompatible.
ERROR: scikit-image 0.17.2 has requirement numpy>=1.15.1, but you'll have numpy
ch is incompatible.

**[Solution]**
Use the following file instead. Version of each component has been set to near the release date of Style2paints V3 (2018.4.28).

`pip install -r requirement_cpu.txt`

requirement_cpu.txt:
```
tensorflow==1.10.0
keras==2.1.6
bottle==0.12.13
gevent==1.2.2
h5py==2.7.1
opencv-python==3.4.0.12
scikit-image==0.13.1
paste==2.0.3
```
