### ISSUE TITLE
[Instruction] Using Docker (V3)

### ISSUE THREAD

**Issue by 5agado** [lllyasviel/style2paints#101]
As done for [Version 1](https://github.com/lllyasviel/style2paints/issues/36) and as required by [Issue 89](https://github.com/lllyasviel/style2paints/issues/89), here a basic Docker setup for Version 3. The setup is for CPU environment, but can be easily adapted for GPU.

If the authors are interested can eventually create a pull request, otherwise you can just do the following

Create *Dockerfile*

```
FROM tensorflow/tensorflow:1.12.0-gpu-py3

RUN apt-get update && \
	apt-get install -y \
		libsm6 libxrender1 libfontconfig1 \
		git vim && \
	rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy and install requirements
COPY requirements.txt ./
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Clone Github repo
RUN git clone https://github.com/lllyasviel/style2paints.git

# Add locally downloaded models
ADD models ./style2paints/V3/server

RUN chown -R 999 /app && \
	chmod -R 777 /app

CMD cd style2paints/V3/server && python server.py -cpu
```

Create *requirements.txt*

```
tensorflow
keras
chainer
bottle
gevent
h5py
opencv-python
paste
scikit-image
# GPU requirements
# tensorflow-gpu
# cupy-cudaXX  # where XX is your cuda version (cupy-cuda90 for cuda 9.0, for example)
```

Place these two files in a directory containing the *models* folder (**you need to download the models yourself**), then execute

    docker build -t style2paint-v3-cpu . # Build Docker image

And run container. The `-v` option is used if you want to mount your `HOST_OUTPUTS_DIR` such that all the app outputs in the container are visible directly from the host machine.

```
HOST_OUTPUTS_DIR=/your/host/outputs/dir/here
docker run \
	--rm \
	-p 8000:80 \
	-v ${HOST_OUTPUTS_DIR}:/app/style2paints/V3/server/results \
	-it style2paint-v3-cpu
```

From the host machine you can then access Style2Paint at http://localhost:8000/

**Comment by mosheliv** [comment]
for GPU, it should be "tensorflow-gpu" and not "tensorflow_gpu" and "cupy-cudaXX" where XX is your cuda version (cupy-cuda90 for cuda 9.0, for example)

**Comment by 5agado** [comment]
> for GPU, it should be "tensorflow-gpu" and not "tensorflow_gpu" and "cupy-cudaXX" where XX is your cuda version (cupy-cuda90 for cuda 9.0, for example)

Fixed as suggested, thanks.
