### ISSUE TITLE
A question about V5 (Not a problem related question)

### ISSUE THREAD

**Issue by SydW23** [lllyasviel/style2paints#103]
I heard Style2PaintsV5 can help users draw but I’m wondering how. I always dreamed about a specific program doing this kind of thing. So would V5 like redraw the image based from user input? 

![f85de271-d830-4132-b523-6d2ac5ed7791](https://user-images.githubusercontent.com/47169001/51960175-6e9dd600-241d-11e9-817c-3a2066926849.jpeg)

**Comment by gceboh** [comment]
https://github.com/youyuge34/PI-REC
This repo may help you, but still in early research stage.
