### ISSUE TITLE
donate link is unavailable

### ISSUE THREAD

**Issue by yinyue200** [lllyasviel/style2paints#104]
Error 520 Ray ID: 4a1994e78ba55408 • 2019-01-31 04:55:01 UTC
Web server is returning an unknown error

**Comment by MuQQQQQ** [comment]
Me too...
搭了梯子也不行

**Comment by SNSLogty** [comment]
> Me too...
> 搭了梯子也不行
链接裸连有效
![pic](http://img04.sogoucdn.com/app/a/100520146/8eadd3ad0efc8435f5a8211d4d95eb7e)
patreon可能在中国电信网络难以访问

**Comment by SNSLogty** [comment]
Now all the donate link was closed,please wait until the v4 version released

**Comment by Tigger-TH** [comment]
Is there still a donation link at the moment?
