### ISSUE TITLE
Win 7 64 bit Image Resizing Issue

### ISSUE THREAD

**Issue by DavidsonAudioMulti** [lllyasviel/style2paints#105]
Hello I was able to use the no install cpu version V3 and it seems to work great except one thing. It resizes the image to a little larger than original. For instance a 834X1200 image will download or finish with a result result of 1024x1432. Is there a way to maintain original image size or specify result size?  Or is there a recommended size of image that won't be resized or am I having an error that others are not having? Thanks for any help on this matter and I can't wait to try V4 and V5 this is amazing thank you thank you!!!

**Comment by stefnotch** [comment]
The resizing seems to be because power of 2 sizes are usually preferable. Try uploading an image with a size of 1024x1024 and see if it also gets resized.

**Comment by DavidsonAudioMulti** [comment]
I tried a .png image that was 1024x 1024 and it worked did not resize this time thank you again. I like to use a vector of the line drawing and place it over finished result I prefer this over emphasize outline option in some cases. Keeping the same size makes it easier to line up both images without resizing.
