### ISSUE TITLE
resize.cpp:3785: error: (-215:Assertion failed)

### ISSUE THREAD

**Issue by banyet1** [lllyasviel/style2paints#106]
It's seemed running smoothly, until this. (just follow "Get Start")

OpenCV(4.0.0) /io/opencv/modules/imgproc/src/resize.cpp:3785: error: (-215:Assertion failed) !dsize.empty() || (inv_scale_x > 0 && inv_scale_y > 0) in function 'resize'

Ubuntu 18.04, how can I solve it?

Thanks.

**Comment by banyet1** [comment]
I knew it, juest switch to python3.

**Comment by wwq98** [comment]
how do you solve it?i have the same problem

**Comment by MX-Qulin** [comment]
> 
> 
> It's seemed running smoothly, until this. (just follow "Get Start")
> 
> OpenCV(4.0.0) /io/opencv/modules/imgproc/src/resize.cpp:3785: error: (-215:Assertion failed) !dsize.empty() || (inv_scale_x > 0 && inv_scale_y > 0) in function 'resize'
> 
> Ubuntu 18.04, how can I solve it?
> 
> Thanks.

Could you tell me if it's smooth to use style2paints on Ubuntu18.04?
I mean to run on a Ubuntu 18.04 Server.
