### ISSUE TITLE
Any updates on V4/V5?

### ISSUE THREAD

**Issue by mocat15** [lllyasviel/style2paints#107]
Greetings:

I am so happy that I got V3/Style Painter to work.  Now I just need to learn how to color with it.

Any update on the status of the paper and release of V4/V5?

Thank you in advance.

**Comment by SNSLogty** [comment]
follow our [Twitter](https://twitter.com/IlIIlIIIllIllII) or [Weibo](https://weibo.com/style2paints) to get the latest news of s2p

**Comment by BlohoJo** [comment]
Somehow I knew when the server was taken down that it wouldn't be coming back, nor would any public release of anything above version 2.
