### ISSUE TITLE
A verification error occurred during decompression and Large green blocks appear when running the program

### ISSUE THREAD

**Issue by meteorlin** [lllyasviel/style2paints#108]
![解压error](https://user-images.githubusercontent.com/49402403/55727464-a12f0500-5a44-11e9-9670-f1421bf9310e.png)
![上色error](https://user-images.githubusercontent.com/49402403/55727466-a1c79b80-5a44-11e9-88e1-7c40a872e98f.png)
These problems really worry me T^T

**Comment by abdellbobo** [comment]
from where did you download s2p ?

**Comment by meteorlin** [comment]
from this website: https://github.com/SNSLogty/style2paints_v3_launcher

**Comment by SNSLogty** [comment]
@meteorlin This repo has stopped after v4-web open. And it was outdated.Please follow issue#100 to get s2p-v3

**Comment by stefnotch** [comment]
Link to issue #100
