### ISSUE TITLE
About the V3 paper.

### ISSUE THREAD

**Issue by mariolew** [lllyasviel/style2paints#110]
Hi, thanks for sharing the great work. Now I've read the V3 paper, as described in the paper, there are only 2 models, but in this project , there are 6 models, I'm just confused. Could you please explain this for me?

**Comment by lllyasviel** [comment]
The paper describes the novelty in V3, but the repo is focused on functionality and includes many other applications that is not in the paper, e.g., style/color transfer, re-coloring, etc..

In particular:

line_head.net: a model to extract line drawings from illustrations, serving for re-coloring.

X_tail.net: super resolution and denoising models.

Gate_head, base_neck: refinement models.

Bae_head, dull_head: drafting models.

We use different combinations to satisfy different use cases.

This repo is designed for artistic use, but not for machine learning research, thusly it is a bit messy. If you are interested in the technique details, it is highly recommended to mainly focused on the paper, where the novelty is well-organized.

BTW, if you are seeking a off-the-shelf repo, you may check Pix2Pix-HD and Pix2Pix.

**Comment by mariolew** [comment]
Great. Thank you.
