### ISSUE TITLE
non-responsive, see preparing and downloading bars but no result

### ISSUE THREAD

**Issue by carroz** [lllyasviel/style2paints#114]
![Screenshot_3](https://user-images.githubusercontent.com/29169292/57980010-32ee4280-79f3-11e9-9042-002b6701070d.png)
using no-install, stuck on this screen.

`
C:\Users\Chill\Downloads\style2paints_noinstall>cd server

C:\Users\Chill\Downloads\style2paints_noinstall\server>..\python\python.exe server.py
Using TensorFlow backend.
2019-05-19 04:58:06.807393: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
C:\Users\Chill\Downloads\style2paints_noinstall\python\lib\site-packages\keras\engine\saving.py:270: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
Bottle v0.12.13 server starting up (using PasteServer())...
Listening on http://0.0.0.0:8000/
Hit Ctrl-C to quit.

serving on 0.0.0.0:8000 view at http://127.0.0.1:8000
127.0.0.1 - - [19/May/2019:04:58:38 -0400] "GET / HTTP/1.1" 304 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36"
127.0.0.1 - - [19/May/2019:04:58:38 -0400] "GET /favicon.ico HTTP/1.1" 200 16958 "http://127.0.0.1:8000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36"
127.0.0.1 - - [19/May/2019:04:58:39 -0400] "POST /get_sample_list HTTP/1.1" 200 2 "http://127.0.0.1:8000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36"
127.0.0.1 - - [19/May/2019:04:58:41 -0400] "POST /get_sample_list HTTP/1.1" 200 2 "http://127.0.0.1:8000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36"
127.0.0.1 - - [19/May/2019:04:58:43 -0400] "GET /res/raw-assets/texture/ring.png?t=0.8899580583204376 HTTP/1.1" 200 113227 "http://127.0.0.1:8000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36"
original_sketch saved
sketch upload pool get request: colorization
processing sketch in ./gamerooms/May19H04M58S44R214
std = 1.2133245`

**Comment by viet1pro** [comment]
What is your pc information.
I think without GPU you need to wait.

**Comment by carroz** [comment]
i have a gtx 1060 6gb and am on cuda

**Comment by viet1pro** [comment]
No-install just apply for cpu, you should install by yourself

**Comment by viet1pro** [comment]
If you have any problem, ask me because i have many problem when i install too XD

**Comment by carroz** [comment]
@viet1pro how can i make sure it is running on gpu? i tried install by myself and now it is stuck on preparing, with no command prompt feedback

**Comment by viet1pro** [comment]
@carroz If you see this line
`Found device 0 with properties:   name: your gpu name`
after this line:
`Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2`
that is it running on your GPU

**Comment by AhdioHore** [comment]
<-- bows & tips hat in your general direction TyTy
