### ISSUE TITLE
Save hint for later use

### ISSUE THREAD

**Issue by viet1pro** [lllyasviel/style2paints#116]
I want to save hint for next time use because i can't open my pc for all day when i go to study.
Can i have way to do that?

**Comment by SNSLogty** [comment]
save hint is available in v4, v3 is too old so it has many shortage

**Comment by viet1pro** [comment]
@SNSLogty Thank you

**Comment by viet1pro** [comment]
@SNSLogty Can i ask your one more question? How can i train my own `.net` file for V3?
