### ISSUE TITLE
纸片协会备用公告板

### ISSUE THREAD

**Issue by lllyasviel** [lllyasviel/style2paints#119]
这里是纸片协会备用公告板。这个Issue将会从6月5号启用，在6月15号解除。届时纸片协会主群，分群，功能群等的所有公告都将会在这里公布。

请群员将这个issue的网址加入收藏栏。如果纸片协会主群，分群，功能群等的所有群出现任何异常我们将会在这里公示预案。

这个issue在一段时间后会删除。

请全体群员切忌在6月5号到20期间在群内发布任何（包括擦边球）的低俗，车，政治，信仰，防火墙等敏感话题。

**Comment by lllyasviel** [comment]
请不要在这个issue里面回复。

**Comment by onsoho** [comment]
谢谢你的工作。<3
