### ISSUE TITLE
User Guidelines 使用说明

### ISSUE THREAD

**Issue by lllyasviel** [lllyasviel/style2paints#12]
**English Version is below to this chinese version**

![image](https://user-images.githubusercontent.com/19834515/30679525-bf221140-9ecc-11e7-96de-666f74d3ed69.png)

简单的说就是先上传一张参考图，再上传一张线稿，再点击上色就好了。

![image](https://user-images.githubusercontent.com/19834515/30679570-f96a6f8c-9ecc-11e7-8bf2-d8fa427f769e.png)

需要注意的是，在你上传参考图之后，你的参考图就会变成一个调色板，可以点击，然后就可以用选好的颜色在线稿上面画点。

![image](https://user-images.githubusercontent.com/19834515/30679618-43f06ee4-9ecd-11e7-9634-3f6784cd61d2.png)

具体用法是点击参考图上的颜色，然后点击线稿上面对应的点，然后就可以给AI颜色参考。

![image](https://user-images.githubusercontent.com/19834515/30679661-859fcde4-9ecd-11e7-9c92-197d128fbe3c.png)

通过这样的点击，就可以给AI各种提示。

![image](https://user-images.githubusercontent.com/19834515/30679698-cc1e574a-9ecd-11e7-89cf-fc044495ce9e.png)

需要注意的是，AI对于这些点十分敏感，只需要轻轻的点击一个很小的点就能起到很大的效果，所以建议只点击几次鼠标。（上面那个图片中就是一个小的点，一般点这么小一个点就够了）

![image](https://user-images.githubusercontent.com/19834515/30679720-f6d58b5c-9ecd-11e7-868c-003fd1a04d66.png)

这四个选项非常重要，用法是先换选项卡再点击上色。

![image](https://user-images.githubusercontent.com/19834515/30679743-273f8f54-9ece-11e7-8109-d21a22eecf65.png)

有的时候切换选项会产生巨大的改变。比如这样：

![image](https://user-images.githubusercontent.com/19834515/30679770-5235852e-9ece-11e7-86b2-94c22712d752.png)
![image](https://user-images.githubusercontent.com/19834515/30679784-6f85b70c-9ece-11e7-8cf3-caaa1f416530.png)

总之建议对于每张线稿都试试所有的V1,V2,V3,V4。

![image](https://user-images.githubusercontent.com/19834515/30776135-d901e848-a0d3-11e7-8b48-01db6dcd4c65.png)
另外这个选项可以给图片降噪，建议试试看。

应该会有所改善。

**Comment by lllyasviel** [comment]
![image](https://user-images.githubusercontent.com/19834515/30679525-bf221140-9ecc-11e7-96de-666f74d3ed69.png)

In short, you can upload a sketch and a reference, and just click colorize.

![image](https://user-images.githubusercontent.com/19834515/30679570-f96a6f8c-9ecc-11e7-8bf2-d8fa427f769e.png)

What is important is that your reference image will become a color picker once it is uploaded. You can select any color via clicking your reference image and give hint to the AI via clicking your sketch, just like paintschainer.

![image](https://user-images.githubusercontent.com/19834515/30679618-43f06ee4-9ecd-11e7-9634-3f6784cd61d2.png)


Just click the reference and then make some pointed hints on your sketch.

![image](https://user-images.githubusercontent.com/19834515/30679661-859fcde4-9ecd-11e7-9c92-197d128fbe3c.png)

You can give the AI many hints like this.

![image](https://user-images.githubusercontent.com/19834515/30679698-cc1e574a-9ecd-11e7-89cf-fc044495ce9e.png)

But keep in mind that the AI is very sensitive to your hints. In most cases, a single and small point is fine. You do not need to so much some messy hints to cover sketch blocks. Small and pointed hints are recommended.

![image](https://user-images.githubusercontent.com/19834515/30679720-f6d58b5c-9ecd-11e7-868c-003fd1a04d66.png)

These 4 toggles are very important.

![image](https://user-images.githubusercontent.com/19834515/30679743-273f8f54-9ece-11e7-8109-d21a22eecf65.png)

In some cases, shifting these toggles will make a big improvement in colorization.

![image](https://user-images.githubusercontent.com/19834515/30679770-5235852e-9ece-11e7-86b2-94c22712d752.png)
![image](https://user-images.githubusercontent.com/19834515/30679784-6f85b70c-9ece-11e7-8cf3-caaa1f416530.png)

So we recommend you try all of these V1, V2, V3, V4 for your sketches.

Good luck and have fun.

**Comment by NoahDragon** [comment]
I think it is better to include into the repo, so create a PR for this https://github.com/lllyasviel/style2paints/pull/15

Moreover, could you please explain more about the V1-V4 options?

**Comment by Brunhilo** [comment]
I don’t know how to use it.I have no idea program.Please help me.
