### ISSUE TITLE
Is it possible to add support for animation-making?

### ISSUE THREAD

**Issue by Little-Electria** [lllyasviel/style2paints#121]
I style2paint has already been an extraordinary tool in painting for animation-making (which has a lot of pictures to draw), especially when combined with cacani (which can generate in-between frames（中割/中间帧 )）
With this combination, It is even possible to make a animation in impasto（厚塗）！

V3 is a good tool for static image colouring;
Though, using it to colour for animation may be a little difficult...

So, is it possible to add the support for animation-making?

**Comment by Little-Electria** [comment]
Well, this animation support is about the client(js)...
And the core and most difficult part of this project is about the server(py).

So, I think it may not be too difficult to code for this function.

The only problem is how to support the animation-making. Is about the GUI and need design. Yes?
Is there anyone who want to design the animation-colouring GUI?

If nobody want to do this, I may design it someday... Sooner or later.

**Comment by viet1pro** [comment]
I think that if you want to do this you will need a lot of compute power(for automatic make a new frame from previous frame's hint)

**Comment by Little-Electria** [comment]
> I think that if you want to do this you will need a lot of compute power(for automatic make a new frame from previous frame's hint)

well, maybe

**Comment by 78Alpha** [comment]
The difference between static and animated is tremendous for an application like this. As it is now, there would be no consistency of color for each frame, even if selected from the same swatch. If it were simply added at this moment, the color would change frame be frame and "smear" frames would be atrocious. It would indeed need hinting of some kind, but that is a whole set of other issues.

**Comment by natowi** [comment]
Here is a draft on the topic: https://github.com/SerialLain3170/Colorization/tree/master/reference_video
