### ISSUE TITLE
V3如何保存中间那副画

### ISSUE THREAD

**Issue by exi3t** [lllyasviel/style2paints#125]
如果点击右上角的下载按钮,只能保存最右边的那副,那怎么保存中间那副?

**Comment by exi3t** [comment]
I mean, how to save the middle one?
![D4CF3F3F54A856308882C558AD8A0145](https://user-images.githubusercontent.com/35194938/62855684-74a63500-bd25-11e9-962b-75e1aef22aeb.jpg)

**Comment by stefnotch** [comment]
Usually you can save images by right clicking on them and pressing "Save image as"

**Comment by Ben76904** [comment]
Not sure if this is how but I go to "style2paints-master" folder then open: \V3\server\game\rooms. You'll find it there but a small rendering size. 
Also other renderings can be found in: style2paints-master\V3\server\results
Not sure other than that.
