### ISSUE TITLE
How to Launch Style2Paints V3?

### ISSUE THREAD

**Issue by SydKid23** [lllyasviel/style2paints#128]
I installed everything but i don't how to launch it. Help????

**Comment by viet1pro** [comment]
Can you provide more information like log???

**Comment by SydWil223** [comment]
Hey, I figured it out! However, it wouldn't work because I didn't have cuda
.

**Comment by jeef518** [comment]
conda install tensorflow-gpu  ok!

**Comment by Wildwizard404** [comment]
use pip or conda to install  
1. tensorflow_gpu
2. keras
3. bottle
4. gevent
5. h5py
6. paste
7. opencv-python
8. scikit-image 
AND YOU NEED TO INSTALL CUDA AND cuDNN from nVidia's website.
then run server.py in server folder.
If you can read Chinese, have a look at [this](https://wildwizard.cn/2019/09/28/%e6%96%b0%e6%89%8b%e5%90%91%e7%9a%84ai%e7%ba%bf%e7%a8%bf%e4%b8%8a%e8%89%b2%e5%ae%89%e8%a3%85/)

**Comment by 78Alpha** [comment]
Sadly, it looks like it doesn't work anymore. Proceeds to spew out an error that it can't decode a 'str' object. This supposed 'str' object is found in baby.net model.

**Comment by gceboh** [comment]
@78Alpha 
Could you describe the steps to reproduce the error in detail and provide detailed log?

For the latest installation note of Style2Paints V3, [this issue](https://github.com/lllyasviel/style2paints/issues/100#issuecomment-645709881) may help you.

**Comment by 78Alpha** [comment]
> @78Alpha 
> Could you describe the steps to reproduce the error in detail and provide detailed log?
> 
> For the latest installation note of Style2Paints V3, [this issue](https://github.com/lllyasviel/style2paints/issues/100#issuecomment-645709881) may help you.

That's actually the guide I followed

Made a VENV with PyCharm.

Is a log automatically made that I didn't see?

**Comment by gceboh** [comment]
What I mean is that the info provided is too brief, so I can't diagnose the problem:

> it can't decode a 'str' object. This supposed 'str' object is found in baby.net model.

<br/>

Could you **copy all the information** that printed in the **Run** tool window of PyCharm, and then post them here?
Run tool window in PyCharm is like this:
![Run tool window](https://www.jetbrains.com/help/img/idea/2020.2/py_run_car_console.png)

After executing `server/server.py`, normally it will print the following info:
```
E:\Programs\VirtualEnvs\s2p_v3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conve
rsion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In
 future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
WARNING:tensorflow:From E:\Programs\VirtualEnvs\s2p_v3\lib\site-packages\tensorflow\python
\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is
deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
E:\Programs\VirtualEnvs\s2p_v3\lib\site-packages\keras\models.py:282: UserWarning: No trai
ning configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
Bottle v0.12.13 server starting up (using PasteServer())...
Listening on http://0.0.0.0:80/
Hit Ctrl-C to quit.

serving on 0.0.0.0:80 view at http://127.0.0.1:80
```

**Comment by gceboh** [comment]
And please check the md5 of `baby.net`, to make sure the file is not broken while the download process.
The correct md5  of `baby.net` is the following: `101C1A319C03D5F81E346B4C4F816D92`

**Comment by 78Alpha** [comment]
The hash of baby.net passed no problem, tried running the server again, still had the same issue. Might have to try running it with conda, but in the meantime, the error output as small as I can make it.

`Traceback (most recent call last):
  File "C:/Users/prome/PycharmProjects/Style2Paints/V3/server/server.py", line 16, in <module>
    from ai import *
  File "C:\Users\prome\PycharmProjects\Style2Paints\V3\server\ai.py", line 50, in <module>
    baby = load_model('baby.net')
  File "C:\Users\prome\PycharmProjects\Style2Paints\venv\lib\site-packages\keras\models.py", line 141, in load_model
    model_config = json.loads(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'`

It worked on one of my prior installs, but this latest one is having issues. Although the environment gets setup the same every time, so there shouldn't be any unexpected differences.

**Comment by gceboh** [comment]
The following `requirement_cpu.txt` will cause the bug.
```
tensorflow==1.10.0
keras==2.1.6
bottle
gevent
h5py
opencv-python
scikit-image
paste
```
error:
```
Using TensorFlow backend.
loading baby.net (1/6)
Traceback (most recent call last):
  File "server.py", line 16, in <module>
    from ai import *
  File "E:\Style2paints-V3\server\ai.py", line 51, in <module>
    baby = load_model('baby.net')
  File "E:\Programs\VirtualEnvs\s2p_v3_test\lib\site-packages\keras\models.py", line 269, in load_mo
del
    model_config = json.loads(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'
```

**[Solution]**
Please use the following `requirement_cpu.txt` instead.

`pip install -r requirement_cpu.txt`

requirement_cpu.txt:(from this [comment](https://github.com/lllyasviel/style2paints/issues/100#issuecomment-645709881))
```
tensorflow==1.10.0
keras==2.1.6
bottle==0.12.13
gevent==1.2.2
h5py==2.7.1
opencv-python==3.4.0.12
scikit-image==0.13.1
paste==2.0.3
```
