### ISSUE TITLE
Website offline

### ISSUE THREAD

**Issue by caoli5288** [lllyasviel/style2paints#129]
![图片](https://user-images.githubusercontent.com/3120587/66637708-2094cf80-ec46-11e9-8293-6bc88addcfa2.png)

**Comment by stefnotch** [comment]
> The server of Style2paintsV4 (s2p.moe) is currently shut down because we do not have enough money. The GPU server (1000USD/MONTH) is costly.

As stated in the first line of the README.md

**Comment by caoli5288** [comment]
@stefnotch So why not remove hyperlink shown in project description?

**Comment by SNSLogty** [comment]
> @stefnotch So why not remove hyperlink shown in project description?

Because it is an official domain of project s2p.We may update the website when we have new version.

**Comment by MX-Qulin** [comment]
> 
> 
> > The server of Style2paintsV4 (s2p.moe) is currently shut down because we do not have enough money. The GPU server (1000USD/MONTH) is costly.
> 
> As stated in the first line of the README.md

Why not use CPU?? Slow is not a problem you know:) (for the network in CHN made me feel free with speed~)
