### ISSUE TITLE
Tweak resolution and dimensions of output

### ISSUE THREAD

**Issue by JosiMou** [lllyasviel/style2paints#132]
Hey - is there a way to tweak the DPI and the dimensions of the output? The output I generate now is a bit blurry and not clear.

**Comment by jshamble** [comment]
I'm having the same issue - the export images are not the same resolution as the upload ones - they seem to be downsampled. At the very least, would like to have them exported at the original dimensions.

**Comment by gceboh** [comment]
# Workaround
[waifu2x](http://waifu2x.udp.jp/)
https://github.com/nagadomi/waifu2x

**Comment by jshamble** [comment]
I found a windows version of waifu2x, hope this helps:
[https://github.com/Specy-wot/Scapix](https://github.com/Specy-wot/Scapix)
