### ISSUE TITLE
V4.5左边的那些预置的调色板是怎么生成的

### ISSUE THREAD

**Issue by NaughtDZ** [lllyasviel/style2paints#134]
我想自己找几个配色画风差不多的图生成调色板，有方法嘛

**Comment by lllyasviel** [comment]
左下直接上传任何图片可以直接作为颜色参考图


 
---原始邮件---
发件人: "NaughtDZ"<notifications@github.com&gt;
发送时间: 2019年12月16日(星期一) 晚上10:15
收件人: "lllyasviel/style2paints"<style2paints@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [lllyasviel/style2paints] V4.5左边的那些预置的调色板是怎么生成的 (#134)



我想自己找几个配色画风差不多的图生成调色板，有方法嘛
