### ISSUE TITLE
 the ”Guide decoder 1” and ”Guide decoder 2”

### ISSUE THREAD

**Issue by qinghua2016** [lllyasviel/style2paints#14]
As is depicted in the paper, you implemented two additional loss, in the ”Guide decoder 1” and ”Guide decoder 2”. But I can not figure out the structure of  ”Guide decoder 1” and ”Guide decoder 2”. Could you tell me how to compute the  ”Guide decoder 1” and ”Guide decoder 2” loss ?

**Comment by lllyasviel** [comment]
![image](https://user-images.githubusercontent.com/19834515/30697091-5a9f41a4-9f10-11e7-9cb7-abcd818960f3.png)

![image](https://user-images.githubusercontent.com/19834515/30697136-833943bc-9f10-11e7-9097-f5be30152134.png)

**Comment by qinghua2016** [comment]
As what I know the base generator network is loaded by base_generator.net.  I am wondering  how to add the guide decoder in the residual u-net, could you give a description about the structure of base_generator ?

**Comment by lllyasviel** [comment]
You can join our community to chat with these techinico technological topic.
Or you may need to wait for our new paper for detailed infomation.

**Comment by qinghua2016** [comment]
Do you mean joining the qq group?

**Comment by qinghua2016** [comment]
Hoping for you new paper!

**Comment by lllyasviel** [comment]
Yes and you are welcome.Closed.
