### ISSUE TITLE
Missing lighting/shading tools...

### ISSUE THREAD

**Issue by GOvEy1nw** [lllyasviel/style2paints#140]
Hi, I can't seem to see any lighting/shading tools in 4.5 have they been removed?

**Comment by mafima** [comment]
wondering the same thing. are we missing something?

**Comment by gceboh** [comment]
May be this repo: [PaintingLight](https://github.com/lllyasviel/PaintingLight). I'm not so sure.

**Comment by gceboh** [comment]
**Every line of code requires hard working.**
Whether style2paints's "lighting/shading tools" is open source or not, we should be **grateful** to the authors for providing this excellent colorization project!

**Comment by GOvEy1nw** [comment]
> **Every line of code requires hard working.**
> Whether style2paints's "lighting/shading tools" is open source or not, we should be **grateful** to the authors for providing this excellent colorization project!

Cool story bro, but the reason I asked is because it used to have that feature & now it doesn't, so I'm inquiring about it's whereabouts/future, chill.

**Comment by lllyasviel** [comment]
The shading tool is removed because it is not stable enough. Because this offline version does not have automatic updating feature, I removed it from 4.5 and will add it back in further versions once it is stable. You may also interested in this project from the community: https://cal.cs.umbc.edu/Papers/Zheng-2020-Shade/

**Comment by CCCassie** [comment]
stop sending letters to me!------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;lllyasviel&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年5月21日(星期四) 晚上9:05
收件人:&nbsp;&quot;lllyasviel/style2paints&quot;<style2paints@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [lllyasviel/style2paints] Missing lighting/shading tools... (#140)
