### ISSUE TITLE
It doesn't use my GPU only CPU

### ISSUE THREAD

**Issue by KAMAL-Data** [lllyasviel/style2paints#141]
Using CPU Trunks.
Loaded some basic models.
Loaded - Style2Paints Deep Learning Engine V45 - CPU
Deep learning modules are ready.

How can I change it to GPU? I checked my task manager, and it uses only 4% of my Nvidia GPU but 90-100% of cpu

**Comment by hoangvietfreelancer** [comment]
Has you change your GPU to show CUDA use in task manager?
![Inked1_VIqM30trxba9CYoNn2iBTA_LI](https://user-images.githubusercontent.com/29736874/82565626-ed83c880-9ba4-11ea-978f-1d903eb2dc84.jpg)

**Comment by KAMAL-Data** [comment]
I can't find it maybe because I don't have cuda software?
 
![image](https://user-images.githubusercontent.com/64566758/82624689-bd531e80-9bd2-11ea-8816-b2521e3b2de2.png)

The usage of gpu went a little bit up to 14-26% but I think it's still not normal

**Comment by lllyasviel** [comment]
The current version does not support 950M. This is because of some Nvidia graphic card capability constraints. We are working on it to improve the performance on old cards.

**Comment by gceboh** [comment]
Current workaround for NVIDIA GTX 950M users:
[[Performance Tuning] Workarounds for Integrated Graphics/AMD GPU Users](https://github.com/lllyasviel/style2paints/issues/146)
