### ISSUE TITLE
No shading funcitonality as per Readme.

### ISSUE THREAD

**Issue by Seedmanc** [lllyasviel/style2paints#152]
The Readme claims that there's not only coloring but also shading functionality, however in the linked v4.5 it could not be found, while the video mentioned there is no longer available. 

From what I found in other videos online, shading was already available in v4.1.8, why was it removed in 4.5b?

**Comment by gceboh** [comment]
https://github.com/lllyasviel/style2paints/issues/140#issuecomment-632072647

**Comment by Seedmanc** [comment]
Is there a way to download a compiled old version? Since the videos weren't made by the creators (I think), it must've been distributed.

**Comment by gceboh** [comment]
Style2Paints V4, which contained the shading algorithm, was provided as an online service around the year of 2018 (No offline version). Now, the GPU server has been shut down due to high fee.
Perhaps [DeepNormals](https://github.com/V-Sense/DeepNormals) may offer some lighting effect.
