### ISSUE TITLE
Insert specific colors - HEX | RBG | HSL?

### ISSUE THREAD

**Issue by joserick** [lllyasviel/style2paints#154]
Is possible to insert specific colors in style2paints? Either in Hex, RGB or HSL?

**Comment by gceboh** [comment]
The following feature may help you, which is not introduced in the [official tutorial](https://style2paints.github.io/). 
This feature is very useful for non-artist users.

After uploading a **customized reference image**, users can **pick color from the thumbnail of the reference image** at the upper left corner, by clicking a specific pixel of the thumbnail.
![thumbnail](https://user-images.githubusercontent.com/29419865/108942556-2b60d080-7692-11eb-997d-a6ef8df96410.png)

While the cursor moving across the reference image, current color under the cursor is shown here (at upper right corner):
![2-2](https://user-images.githubusercontent.com/29419865/108942597-3d427380-7692-11eb-8db2-4c0daa03a055.png)

**Comment by gceboh** [comment]
And note that before using this feature, please try to pick color from the canvas (auto colorization result) first.

**Comment by joserick** [comment]
Thank you very much, this will be a great help for my next Recolored, it would be nice if made a little comment on this in the next tutorial update.

But it would be good that in the future versions will added a input for insert a specific color (code HEX).

In the end I did it through a command in the web browser console, I leave it here in case someone specifically requires it:
```js
window.minecraft.set_cur_color([198, 164, 218]) // it's in RBG
```
