### ISSUE TITLE
PSD layers?

### ISSUE THREAD

**Issue by natowi** [lllyasviel/style2paints#155]
> Style2paints V4 gives you results of the current highest quality. You are able to get separated layers from our system. These layers can be directly used in your painting workflow. Different from all previous AI driven colorization tools, our results are not single 'JPG/PNG' images, and in fact, our results are 'PSD' layers.

I only get _blended_flat_careful.png, blended_flat_careless.png, blended_smoothed_careful.png, blended_smoothed_careless.png, flat_careful.png, flat_careless.png, smoothed_careful.png, smoothed_careless.png_ from _assets\game\rooms_

Edit: I see, the eight png files are the 'PSD' layers. 

It would be great to have actual layers, one for the sketch and one for the colourisation or even better: one layer for each colour.

**Comment by gceboh** [comment]
**For lighting/shadow layer:**
#152

**For flat coloring layer:**
It seems that it is still under development.
Technical preview: [DanbooRegion](https://github.com/lllyasviel/DanbooRegion)  (See **10.1 Sketch Colorization**)

**Comment by natowi** [comment]
Thanks, that´s great.
