### ISSUE TITLE
V4.5 InternalError: Could not allocate ndarray

### ISSUE THREAD

**Issue by zensiangliao** [lllyasviel/style2paints#156]
Can't open s2pV4.5 on my Windows 10 notebook.

It shows a line:

tensorflow.python.framework.errors_impl. InternalError: Could not allocate ndarray
[12184] Failed to execute script Style2PaintsV45

Need help QAQ

**Comment by gceboh** [comment]
Hardware environment?
GPU memory may be not enough.
And 4~5G free RAM is required.
https://github.com/lllyasviel/style2paints/issues/135#issuecomment-631487254

**Comment by gceboh** [comment]
also, make sure your virtual memory setting is big enough, at least 4G
