### ISSUE TITLE
Is there a way to process multiple images at once?

### ISSUE THREAD

**Issue by yenonono** [lllyasviel/style2paints#158]
I'm trying to color a whole stop-motion animation and processing every individual frame will take an extremely long time.
I know the color of the outcome will be inconsistent but right now I'm in a quantity over quality required situation.

**Comment by gceboh** [comment]
**Unofficial reply:**
Please refer to "[About Copyright](https://github.com/lllyasviel/style2paints#about-copyright)" section in readme.md:

Furthermore, if you want to use our software in **large-scale** commercial or industrial production or publication, e.g. manga (entity paper manga or online e-manga), magazine, book or other online/offline large-scale materials, **please contact us for permission.**
With our permission, you can enjoy more professional services with our cutting-edge technologies. Please do not use our software for large-scale commercial or industrial publications without our approval.
