### ISSUE TITLE
youtube link on readme does not work.

### ISSUE THREAD

**Issue by starinspace** [lllyasviel/style2paints#160]
The video on your page here is set to private.

**Comment by Seedmanc** [comment]
That's cause they took the shading away from us and would rather prefer us to think it never existed. The video featured it.

**Comment by starinspace** [comment]
> That's cause they took the shading away from us and would rather prefer us to think it never existed. The video featured it.

I don't really understand what you mean. But that's not good. I hope they will make it public again, i prefer the original before other who mess around even if that's good too.
