### ISSUE TITLE
Better pallets

### ISSUE THREAD

**Issue by MatteCrystal** [lllyasviel/style2paints#161]
Can we get a revamped color pallet system? 

Current pallet only allows remembering 5 custom colors which is extremely limiting having an unlimited or at least far larger pallet would be a massive help. Furthermore, you can't paste in hex values. you're forced to use the color wheel a guesstimate the correct color. This is a major issue if u want consistency between multiple images. Please allow the option to select a color via pasting hex value.

Also being able to hit alt to quickly grab the color your hovering is very helpful but it's not helpful when it auto replaces the active pallet color. This means really the 5 custom pallets are really only 4 usable colors at a time because the fifth color is used as a placeholder for active shades/colors u grab using alt. Also you need to remember to manually switch back to this placeholder color swatch each time before using the color picker otherwise you will overwrite 1 of your 4 custom colors. 

Finally, an option to save your current color pallet so you can use it next time you use the program would be really great. 

When I reference color palette I'm referring to this 
![image](https://user-images.githubusercontent.com/32424764/112573080-8e40a700-8db9-11eb-9b2b-5b5f368ca178.png)

**Comment by SkillsH0T** [comment]
Yes, I've faced the same issues. The option to enter the hex value would easily solve many problems regarding details and consistency as you described!
