### ISSUE TITLE
Better Save Options.

### ISSUE THREAD

**Issue by MatteCrystal** [lllyasviel/style2paints#162]
Current save workflow is a major headache. It often takes me a min or longer to make sure I'm saving the correct style and backup a text file of the points. 

Obviously the best option would be a traditional save system that saves the currently selected style. If this is not easily possible though then at the very least do one of the following. Either make the first image at the top of the save page be the same as the currently open style. Or option two, Make the images that appear in the save window appear in the same order as the styles that appear in the program. They way it is now is just a random mix of styles with no apparent order.

Also an option to just save all style versions at once would also be really great.

**Comment by spomacmega** [comment]
i agree. would be nice if the save hint points is just saved on a .txt file and when you need to load, just make the program load the .txt file.

**Comment by gceboh** [comment]
Try to fix it in #157
Hope it is helpful for the future version.
