### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Aspie96** [lllyasviel/style2paints#163]
> Furthermore, if you want to use our software in large-scale commercial or industrial production or publication, e.g. manga (entity paper manga or online e-manga), magazine, book or other online/offline large-scale materials, please contact us for permission:

The license though does allow commercial usage.

The license is misleading or this statement makes no sense

**Comment by EuphoricPenguin** [comment]
Exactly. Not sure what that was about at all. The license should reflect the statements in the README.
