### ISSUE TITLE
Potential Acceleration Solution for AMD GPU / Integrated Graphics

### ISSUE THREAD

**Issue by gceboh** [lllyasviel/style2paints#165]
Potential Acceleration Backend for **new AMD GPU / Integrated Graphics**, which may be helpful.
[DirectML#TensorFlow-with-DirectML-Preview](https://github.com/microsoft/DirectML#TensorFlow-with-DirectML-Preview)
repo: [tensorflow-directml](https://github.com/microsoft/tensorflow-directml). 

It uses Microsoft's DirectX 12, rather than NVIDIA CUDA, to accelerate deep neural network's computation.
(Note that it is **still in the preview stage**.)

```
Requirements:
One of the following supported GPUs:
AMD Radeon R5/R7/R9 2xx series or newer
Intel HD Graphics 5xx or newer
NVIDIA GeForce GTX 9xx series GPU or newer
```

**Users who own the specific GPU and are interested in this, could test it with Style2Paints V3.**
(sorry that I can't test the method, due to lack of specific hardware.)

**Comment by lllyasviel** [comment]
Looks good and I will try it later.

**Comment by lllyasviel** [comment]
Unfortunately Win 7 does not support DirectX 12 but about many my artist friends are still using win 7. And some of them are using something like "win7 + GTX 1050" which is somewhat weird but is the fact.

**Comment by marcussacana** [comment]
It's hard to keep support to both api? not sure, if you that will like double your work.

**Comment by gceboh** [comment]
I noticed that when migrating to `tensorflow-directml`, the device placement in [config.py](https://github.com/lllyasviel/style2paints/blob/master/V3/server/config.py) may need change to `/DML:0`.
(Issue: https://github.com/microsoft/tensorflow-directml/issues/225,  [gpu-faq](https://docs.microsoft.com/en-us/windows/win32/direct3d12/gpu-faq))

I'm not familiar with the `tensorflow-directml`, so I'm not sure how many other changes are needed.

---
PS: DirectML's current shaders are mostly **optimized for inference stage** ([roadmap](https://github.com/microsoft/tensorflow-directml/wiki/Roadmap)), standard or example performance benchmarks that include training stage may be slow. So benchmarks including training process may not be accurate. Style2Paints doesn't need training stage.

I guess on NVIDIA cards, directML may be slower than CUDA. But on AMD GPU / Integrated Graphics, directML  may bring performance gain.

**Comment by gceboh** [comment]
A good news is that: 
migrating to `tensorflow-directml` seems not difficult, the main change in code is only the following: 
(Currently I can't test it, but I infer from other's issue.)

from:
`with tf.device('/GPU:0'): `
to:
`with tf.device('/DML:0'): `

Ref: https://github.com/microsoft/tensorflow-directml/issues/225#issuecomment-840211943

**Comment by straves16** [comment]
[Sound](http://soundcloud.com)
