### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by XinweiChai** [lllyasviel/style2paints#18]
Hello guy, I tried to install all the packages and run python server.py cpu, then it returns the message 'No training configuration found in save file: '. In fact I have no idea how the program functions, could you help me? :)

**Comment by abbychau** [comment]
download in this page https://github.com/lllyasviel/style2paints/releases
and put them inside server folder

**Comment by lllyasviel** [comment]
this is a warning, not a error. just ignore it.
