### ISSUE TITLE
The source code of Style2Paints V4 and V4.5 work properly on Windows 10 with RTX2060. Thanks!

### ISSUE THREAD

**Issue by crodis-strife** [lllyasviel/style2paints#192]
V4: https://www.youtube.com/watch?v=hpnvn60Ki7s
V4.5: https://www.youtube.com/watch?v=FktkmMUEr9o

They are much faster in initialization compared with the exe version.
https://www.youtube.com/watch?v=5L6JzcrW638

**Comment by 78Alpha** [comment]
Would you happen to have an EXE bundle built of V4? I am unable to get it to do much on an RTX 3070 system, however, the V4.5 EXE works.

**Comment by crodis-strife** [comment]
Sorry, I don't have an EXE bunble built of V4. I just run the source code of V4 in Anaconda.

**Comment by 78Alpha** [comment]
Managed to package my own to work with V4, will try to put it in a github fork

**Comment by marcussacana** [comment]
Yup, and works on linux too

**Comment by 78Alpha** [comment]
3070 and above need a patched tensorflow, 1.15 version at cuda 11.1 and python 3.8 support is floating around the tensorflow binary repo.
