### ISSUE TITLE
Unable to run style2paints v4

### ISSUE THREAD

**Issue by My12123** [lllyasviel/style2paints#195]
Unable to run style2paints v4
ERROR: Could not find a version that satisfies the requirement llvmlite==0.36.0rc1 (from versions: 0.2.0, 0.2.1, 0.2.2, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.9.0, 0.10.0, 0.11.0, 0.12.0.1, 0.12.1, 0.13.0, 0.14.0, 0.15.0, 0.16.0, 0.17.0, 0.17.1, 0.18.0, 0.19.0, 0.20.0, 0.21.0, 0.22.0, 0.23.0, 0.23.2, 0.24.0, 0.25.0, 0.26.0, 0.27.0, 0.27.1, 0.28.0, 0.29.0, 0.30.0, 0.31.0, 0.32.0, 0.32.1, 0.33.0, 0.34.0, 0.35.0, 0.36.0)
ERROR: No matching distribution found for llvmlite==0.36.0rc
![2022-07-06_12-55-04](https://user-images.githubusercontent.com/49092250/177525011-a3675272-56d0-429f-995c-2487923edb5c.png)
How do I launch style2paints v4?

**Comment by 78Alpha** [comment]
https://github.com/78Alpha/style2paints-Backup/tree/master/V4

Try this out (the instructions/requirements) or the EXE version, see if that works

**Comment by My12123** [comment]
The EXE file fails, closes. I have the NVIDIA GeForce GTX 1050 video card

**Comment by 78Alpha** [comment]
Yeah, V4 fails on anything that has less than 6 GB VRAM. It would be an XX60 and above. V4.5 seemed to be the one that works on everything, V4 is a resource hog.

**Comment by My12123** [comment]
Can we fix this?
I’ve got six gigabytes of GPU memory.
2 GB of dedicated and 4 GB of general.

**Comment by lllyasviel** [comment]
fixed https://github.com/lllyasviel/style2paints/commit/69444d6c2affa05b43031174747a3a0f25cdc1e5

**Comment by My12123** [comment]
@78Alpha thanks for your help.

**Comment by My12123** [comment]
@lllyasviel with the Google Colab version please help. 
Can I have a link to style2paints v4 for Google Colab?

**Comment by My12123** [comment]
![2022-07-12_18-57-28](https://user-images.githubusercontent.com/49092250/178538978-48dfbeae-e989-4a05-9b20-68b6c565ed14.png)
