### ISSUE TITLE
When will SEPA (style2paints V5) be published?

### ISSUE THREAD

**Issue by My12123** [lllyasviel/style2paints#197]
When will SEPA (style2paints V5) be published? Summer is over.

**Comment by marcussacana** [comment]
![PSX_20220901_115303](https://user-images.githubusercontent.com/10576957/187945322-1287d4d5-afcf-4595-aaac-3e6b74643804.jpg)

**Comment by wolfgangmami** [comment]
> We are still working on that. Two reasons are: (1) recently the field of image generation has seen some new advances (as you know, those big models everywhere in the media and on twitter). We have to make many new attempts. (2) The core member of team, Lvmin Zhang, returned to an university – he is a student again (now for a phd). This doesn't have to result in a delay in the project (as he says), but it should have some influence on the progress.
> 
> We will update a more detailed report in two to three weeks.

Well we can wait that's for sure but when is gonna release remaster version of this ? The program is fine but the UI part is you know kinda sucks

**Comment by Ihateyoudattebayo** [comment]
I think that the style2paints team should release more betas, so we can see improvement as S2P has been in limbo for 4 years.

**Comment by Ihateyoudattebayo** [comment]
> We are still working on that. Two reasons are: (1) recently the field of image generation has seen some new advances (as you know, those big models everywhere in the media and on twitter). We have to make many new attempts. (2) The core member of team, Lvmin Zhang, returned to an university – he is a student again (now for a phd). This doesn't have to result in a delay in the project (as he says), but it should have some influence on the progress.
> 
> We will update a more detailed report in two to three weeks.

3 weeks have passed.

**Comment by ReihanHaekal** [comment]
> 3 weeks have passed.

Really dude 🙄
You're dictating someone to work more on his own free project.

**Comment by lllyasviel** [comment]
We are doing the best we can, but we are also very acutely aware (and sorry about) that we need extra time.

**Comment by Ihateyoudattebayo** [comment]
> 

Take as long as you need,what matters most is a good product.

**Comment by My12123** [comment]
When will SEPA (style2paints V5) be published?
Can you give me the exact date of publication?
@lllyasviel

**Comment by Ihateyoudattebayo** [comment]
> We are doing the best we can, but we are also very acutely aware (and sorry about) that we need extra time.

Can you(S2P research) please give us a small update.

**Comment by lllyasviel** [comment]
closed as new announcement released.
