### ISSUE TITLE
请教两个问题

### ISSUE THREAD

**Issue by DavieHR** [lllyasviel/style2paints#2]
hello, 想问两个问题
１、训练数据的素描图是怎么来的？
２、你们模型画的太赞了，这种三维的图是用什么软件画的？是visio吗

**Comment by lllyasviel** [comment]
我hub里面有个项目叫做sketchKeras
unity3d

**Comment by XinweiChai** [comment]
Hello guy, I tried to run python server.py cpu, and it returns the message 'No training configuration found in save file: '. In fact I have no idea how the program functions, could you help me? :)

**Comment by shenhaiyoualn** [comment]
可以分享下你们Unity的项目文件吗？
万分感谢！
