### ISSUE TITLE
No release date for project SEPA and v4 remaster.

### ISSUE THREAD

**Issue by Ihateyoudattebayo** [lllyasviel/style2paints#200]
There has been no information about the project since the beginning of the fall, and with the year almost coming to an end, I want to know the current state of the project. I am perfectly fine with the project being delayed, I just need more updates and info over the new discoveries, previews over the S2P research.

**Comment by Ihateyoudattebayo** [comment]
Will it be delayed to next summer again?

**Comment by lllyasviel** [comment]
closed as new announcement released.
