### ISSUE TITLE
Could not open ./nets/tail.net,Data loss: 

### ISSUE THREAD

**Issue by chenw966** [lllyasviel/style2paints#203]
V4.5
Could not open ./nets/tail.net, Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?

**Comment by Ihateyoudattebayo** [comment]
What device are you using?

**Comment by chenw966** [comment]
Thank you for your reply. I have solved this problem.

**Comment by xinyeCH** [comment]
@chenw966 I have the same problem, can you tell me how to fix this problem? thanks.

**Comment by chenw966** [comment]
Is the result of painting abnormal? My reason is that gpu does not support tf_ gpu 1.14。 I use the cpu version of tf。
