### ISSUE TITLE
V4.5 bad magic number

### ISSUE THREAD

**Issue by andiabrudan** [lllyasviel/style2paints#221]
Hi all, I'm having issues running the project straight from the repository (as opposed to running the precompiled executable shipped via Google/Baidu drive)

My machine:
```
Windows x64
Intel i9 12900KF
Nvidia RTX 3080Ti
32Gb DDR5 @6400Mhz
```

Here are the steps that I took:
 - Clone the repository
 - Download the archive from Google Drive and move `Downloads\style2paints45beta1214B\assets\nets` to `style2paints\V4.5\s2p_v45_server\nets`
 - Install Cuda 10.0 from here: developer.nvidia.com/cuda-10.0-download-archive (express install)
 - Add `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0` to PATH so the DLL files could be visible
 - Download CuDNN 7.6.5 from here: https://developer.nvidia.com/rdp/cudnn-archive
(Then move the DLL from `cudnn-10.0-windows10-x64-v7.6.5.32\cuda\bin\cudnn64_7.dll` to the directory mentioned above)
 - Install python 3.6.8 (latest prebuilt 3.6 binary from python.org)
 - `python36 -m pip install -r requirements.txt`
(Note: I had to modify the requirements file and add `h5py==2.10.0` because any 3.x version causes an issue with tensorflow)
 - `python36 style2paints\V4.5\s2p_v45_server\Style2PaintsV45_source.py`

Here is the output log I got: [style2paints.txt](https://github.com/lllyasviel/style2paints/files/11337791/style2paints.txt)

Please let me know if you see anything wrong with my process.

I have no issues running the precompiled version from the archive, but I'd like to make a few customizations to the project, which that version does not allow.

**Comment by Ihateyoudattebayo** [comment]
> Hi all, I'm having issues running the project straight from the repository (as opposed to running the precompiled executable shipped via Google/Baidu drive)
> 
> My machine:
> 
> ```
> Windows x64
> Intel i9 12900KF
> Nvidia RTX 3080Ti
> 32Gb DDR5 @6400Mhz
> ```
> 
> Here are the steps that I took:
> 
> * Clone the repository
> * Download the archive from Google Drive and move `Downloads\style2paints45beta1214B\assets\nets` to `style2paints\V4.5\s2p_v45_server\nets`
> * Install Cuda 10.0 from here: developer.nvidia.com/cuda-10.0-download-archive (express install)
> * Add `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0` to PATH so the DLL files could be visible
> * Download CuDNN 7.6.5 from here: https://developer.nvidia.com/rdp/cudnn-archive
>   (Then move the DLL from `cudnn-10.0-windows10-x64-v7.6.5.32\cuda\bin\cudnn64_7.dll` to the directory mentioned above)
> * Install python 3.6.8 (latest prebuilt 3.6 binary from python.org)
> * `python36 -m pip install -r requirements.txt`
>   (Note: I had to modify the requirements file and add `h5py==2.10.0` because any 3.x version causes an issue with tensorflow)
> * `python36 style2paints\V4.5\s2p_v45_server\Style2PaintsV45_source.py`
> 
> Here is the output log I got: [style2paints.txt](https://github.com/lllyasviel/style2paints/files/11337791/style2paints.txt)
> 
> Please let me know if you see anything wrong with my process.
> 
> I have no issues running the precompiled version from the archive, but I'd like to make a few customizations to the project, which that version does not allow.

Instead of downloading the files and setting up the environment, just download the exe files present, or get the exe of V 4.0 as V4 is a lot better than V45.

**Comment by andiabrudan** [comment]
I am not aware of any V4.0 exe. The only distributed precompiled executable I've seen is for V4.5
Regardless, I fiddled around with V4.0 for a while. Although I don't get any warnings about the `nets` in 4.0, the output images are mostly static.
Here's an example:
<img src="https://user-images.githubusercontent.com/30932040/235014739-b26b9c8b-3979-48aa-9feb-c50902e2375c.png" width="400">

Every render looks like this or worse. Not sure what I'm doing wrong.
I think I double-checked every part of the installation at this point as well as try different versions of CuDNN or change the `nets`  from the 4.0 ones ([provided here](https://drive.google.com/drive/folders/142ZFZUX1mpf2FOKGhf6Z7aUkQy2wNryF?usp=sharing
)) to the 4.5 ones. Did a clean installation of the graphics driver and reinstalled Cuda10. Always same result. I assume this has more to do with the training data than the software components used.

**Comment by Ihateyoudattebayo** [comment]
> I am not aware of any V4.0 exe. The only distributed precompiled executable I've seen is for V4.5 Regardless, I fiddled around with V4.0 for a while. Although I don't get any warnings about the `nets` in 4.0, the output images are mostly static. Here's an example: <img alt="" width="400" src="https://user-images.githubusercontent.com/30932040/235014739-b26b9c8b-3979-48aa-9feb-c50902e2375c.png">
> 
> Every render looks like this or worse. Not sure what I'm doing wrong. I think I double-checked every part of the installation at this point as well as try different versions of CuDNN or change the `nets` from the 4.0 ones ([provided here](https://drive.google.com/drive/folders/142ZFZUX1mpf2FOKGhf6Z7aUkQy2wNryF?usp=sharing)) to the 4.5 ones. Did a clean installation of the graphics driver and reinstalled Cuda10. Always same result. I assume this has more to do with the training data than the software components used.

here is the v.4 exe file, its not a virus and safe to use

https://drive.google.com/file/d/1O-JTlVR8FFBMh3gQeiBlIAQU8CvrbcZ7/view?usp=sharing

**Comment by andiabrudan** [comment]
Got it working. However, I only managed to make it work on a different machine than my main one, with a 3080Ti.
I suspect there's something wrong with the code detecting a higher end graphics card than there were available at the time of the last commit. The machine it's working on has a 2060 super.
I'll try to debug it and submit a fix.

Also, this link doesn't work for me:
https://drive.google.com/file/d/1O-JTlVR8FFBMh3gQeiBlIAQU8CvrbcZ7/view?usp=sharing
![image](https://user-images.githubusercontent.com/30932040/235252248-aba3e4f5-14e8-40eb-9dd8-ba8cbc70857c.png)

**Comment by FlowRays** [comment]
> Got it working. However, I only managed to make it work on a different machine than my main one, with a 3080Ti. I suspect there's something wrong with the code detecting a higher end graphics card than there were available at the time of the last commit. The machine it's working on has a 2060 super. I'll try to debug it and submit a fix.
> 
> Also, this link doesn't work for me: https://drive.google.com/file/d/1O-JTlVR8FFBMh3gQeiBlIAQU8CvrbcZ7/view?usp=sharing ![image](https://user-images.githubusercontent.com/30932040/235252248-aba3e4f5-14e8-40eb-9dd8-ba8cbc70857c.png)

I meet the same problem with a 3080Ti on style2paints 4.5. Could you share your environment which successfully paints? (style2paints version; graphics card; cuda version; cudnn version; tensorflow or anything else needs attention). thx

**Comment by Ihateyoudattebayo** [comment]
> > Got it working. However, I only managed to make it work on a different machine than my main one, with a 3080Ti. I suspect there's something wrong with the code detecting a higher end graphics card than there were available at the time of the last commit. The machine it's working on has a 2060 super. I'll try to debug it and submit a fix.
> > Also, this link doesn't work for me: https://drive.google.com/file/d/1O-JTlVR8FFBMh3gQeiBlIAQU8CvrbcZ7/view?usp=sharing ![image](https://user-images.githubusercontent.com/30932040/235252248-aba3e4f5-14e8-40eb-9dd8-ba8cbc70857c.png)
> 
> I meet the same problem with a 3080Ti on style2paints 4.5. Could you share your environment which successfully paints? (style2paints version; graphics card; cuda version; cudnn version; tensorflow or anything else needs attention). thx

https://drive.google.com/open?id=1gmg2wwNIp4qMzxqP12SbcmVAHsLt1iRE

**Comment by FlowRays** [comment]
Well, I don't want to use the exe file, instead I'm trying to deploy the app through the source code for learning objective. My problem is that although I successfully run the code but it produces obviously incorrect colorizing results as @andiabrudan mentioned above.
Till now, I find that someone deployed on [huggingface](https://huggingface.co/spaces/HighCWu/Style2Paints-4.5-Gradio/tree/main), maybe I can learn from it. 
Anyway, thanks for your reply.
