### ISSUE TITLE
Data augmentations for Alice model

### ISSUE THREAD

**Issue by harpavatkeerti** [lllyasviel/style2paints#223]
Hi, really intrigued by both the v5 models, especially the Alice model, considering that it can work with very simple or even incomplete inputs. Can you please share some details about the data augmentations that you are using to create the dataset for training this model, as the input sketch can be very abstract and different from the ground truth detailed illustration? 

Also, while we are eagerly waiting for the model release, is there any paper/resource about the methodology behind the v5 models?

Thanks a lot!!!

**Comment by Ihateyoudattebayo** [comment]
> 

He has already released the model on control net v. 1.1 nightly.

I expect the anouncment will be during summer, as lyumin is busy with maintaing the web ui

**Comment by harpavatkeerti** [comment]
Thanks @Ihateyoudattebayo, which is the Alice model amongst those available on ControlNet v1.1  nightly?

**Comment by Ihateyoudattebayo** [comment]
> Thanks @Ihateyoudattebayo, which is the Alice model amongst those available on ControlNet v1.1 nightly?

Its scribble model with some improvements

**Comment by harpavatkeerti** [comment]
Oh ok, thanks a lot !!!
