### ISSUE TITLE
WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost

### ISSUE THREAD

**Issue by kleusbalut** [lllyasviel/style2paints#23]
hello

I'm encountred issue. maybe Browser-Side Error.
Chrome Firebug console logged"WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost".

OS: Windows10 Pro x64 (Build 15063)
Chrome: 61.0.3163.100 (Official Build) 64-bit 

running on style2paints and browser in both machine.

workarounds?

thanks!

**Comment by lllyasviel** [comment]
any screenshot?

**Comment by kleusbalut** [comment]
thanks for replying.

attached after crashed screenshot.


additional informations:

before browser crash, was using "pen" mode.
attach to color in rough sketching.

some works ...but after browser crash, blackout.

![style2paint - google chrome 2017-09-29 21-42-26](https://user-images.githubusercontent.com/9697347/31016351-43a95bf6-a55f-11e7-9303-8335008b435a.png)


and,additional console messages.
"GL_INVALID_OPERATION : glGenSyncTokenCHROMIUM: fence sync must be flushed before generating sync token"

![developer tools - http1270018000 2017-09-29 21-42-04](https://user-images.githubusercontent.com/9697347/31016352-43ac4820-a55f-11e7-91cd-02561ea3bf4b.png)

**Comment by lllyasviel** [comment]
It is strange... I will think of it later. Thank you for reporting.

**Comment by kleusbalut** [comment]
maybe, reason are use pen-tablet.

i'm using WACOM Intuos pen small (CTL-480).

mouse only paint, works well.

**Comment by pokeball99** [comment]
i'm getting the same issue
`cocos2d-js-min.js:1 [Deprecation] The devicemotion event is deprecated on insecure origins, and support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
175.n._registerAccelerometerEvent @ cocos2d-js-min.js:1
/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)
cocos2d-js-min.js:1 Create unpacker 0867b4a41 for 01VQu7+XVJj4beyhMxk53E
cocos2d-js-min.js:1 LoadScene 01VQu7+XVJj4beyhMxk53E: 1999.701171875ms
main.js:140 Success to load scene: db://assets/main.fire
project.js:1 english
paintstransfer.com/:1 GL_INVALID_OPERATION : glGenSyncTokenCHROMIUM: fence sync must be flushed before generating sync token
paintstransfer.com/:1 WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost`
this is what i got in the console, maybe this will help
