### ISSUE TITLE
AI Manga Coloring Community

### ISSUE THREAD

**Issue by adi-panda** [lllyasviel/style2paints#236]
Hey guys, 

If anyone is interested, I made a discord server dedicated to trying to figure out new workflows for coloring manga, if anybody is interested feel free to join here: 

https://discord.gg/xF4ZMnKsAG

**Comment by qingxian233** [comment]
您好(*?0?7▽｀)ノノ青弦已经收到您的邮件啦！请耐心等待，10个工作日内会给您回复w
