### ISSUE TITLE
custom color hints?

### ISSUE THREAD

**Issue by wchristian** [lllyasviel/style2paints#25]
This might not be possible, but who knows. I learned from the nice video you made what the pen tool is for. However there are some restrictions on colors:

- loading a new reference resets color hints
- one cannot set color hints for colors that aren't in the reference

I was hoping that it might be possible to set a white sheet of reference, put color hints on the sketch, and have the NN operate only off the hints, for more targeted selection of colors.

Would this be possible?

**Comment by lllyasviel** [comment]
emmm add arbitary color hints is very uncontrolable and it need the users have professional color knowledge of anime color composition. Colors from ref img are in harmony with eachother in most cases. In our reseach, the nn sometimes resist strongly to color hints not from ref map..

**Comment by abbychau** [comment]
@wchristian 

this actually happens to paintschainer and many other image networks too. 
the hinted color may not be feasible to be happened in some part of the picture and thus a resistance, such as giving a light color at the area that belongs to shadows. 

of course you can extract the hue out but it is just an example to show why it is sometimes impossible. Many hues in certain areas of the drawing is arbitrary to the network from time to time. Just like blue foods(or purple hippo) creates large entropy in your mind. 
And this could also explain the brownish tone of the early paintschainer.

If you find the way to serialize the training items not only in terms of color but other factors, this would be a breakthrough.
