### ISSUE TITLE
colorizing with green heavy images distorts quality?

### ISSUE THREAD

**Issue by pokeball99** [lllyasviel/style2paints#28]
i've been messing with this for the last week and its great, one major problem it seems is that any reference with alot of green, such as with nature scenery causes the colors to mess up pretty badly, even making most of the image a dark black, and even with touching it up the nerual network seems to fight it tooth and nail, perhaps it maybe a relative lack of training data compared to other colored images?
(sorry if this isn't the right place)

**Comment by lllyasviel** [comment]
emmm..... an example ref please?
