### ISSUE TITLE
A question about the last layer in encoder

### ISSUE THREAD

**Issue by harrywang-1523** [lllyasviel/style2paints#3]
May I ask why the size of final layer is **256 * 256 * 64** but not **256 * 256 * 16** ? From my perspective, the layer should become thinner and thinner through the decoder. Also, the picture in the paper shows the final layer is thinner than the previous one.

**Comment by lllyasviel** [comment]
In my opinion, adding channels to the last layer or the second-to-last layer may be helpful for the network to reach a balence between L1 and GAN loss. But recently the stack GAN is well-suited for this.

**Comment by harrywang-1523** [comment]
Thanks for your reply. I would really appreciate it if you could answer the below questions.
1. I am a little confused **why the 32 * 32 * 128 layer at front part does not contribute to u-net decoder at back part**? The 256 * 256 * 16, 128 *  128 * 32, 64 * 64 * 64 and 16 * 16 * 256 layers all contributes to the back part. It seems to me that **the structure of the generator is asymmetric**, which is a little weird to me. 
2. The operands in the first part of the loss function has **unmatched shape**.  y has the shape of **512 * 512 * 3** while Gf(x, V(x)) has the shape of **256 * 256 * 3**. How did you deal with this issue?
<img width="586" alt="screen shot 2017-07-11 at 3 13 46 pm" src="https://user-images.githubusercontent.com/24424127/28055775-fbe64e38-664c-11e7-9259-22ab7efb5f10.png">

**Comment by lllyasviel** [comment]
1.Yes the structure is asymmetric. The encoder has nearly no ability to create paintings. The fusion of the two 8*8*2048 layers is responsible for the main colorization task. The skip-connect layers only "guide" the decoder to spread the color distribution. The input is gray-scaled high-frenquency mat and the output is a colorful mat with either high or low frenquency distrubution, from this perspective, I think the decoder should be more powerful than the encoder.
2.scale it.

**Comment by lllyasviel** [comment]
The network structure has changed a lot. We now use stack GAN for super-resolution and AC W-GAN GP for tuning. Every Layers of VGG all have skip-connections to the encoder of our paints network. We also employs pointed hints like paintsChainer to make the model more productive. Our website is coming soon and all codes will be avalibale.

**Comment by harrywang-1523** [comment]
Thanks. I believe it is going to be a great work. Looking forward to see the code!

**Comment by rahulbaburaj** [comment]
"...Also, the picture in the paper shows the final layer is thinner than the previous one." Which paper are you taking about. Can you share the paper here?
