### ISSUE TITLE
Can style2paints colorize the sketch of landscape?

### ISSUE THREAD

**Issue by lgcagithub** [lllyasviel/style2paints#30]
Can style2paints colorize the sketch of landscape?

**Comment by lllyasviel** [comment]
It cannot because all training data are anime paintings.

**Comment by lgcagithub** [comment]
But if I use landscape to train it, does it help?

**Comment by lllyasviel** [comment]
landscape colorization is very easy to pix2pix or CycleGAN. Beginners can easily make their own datasets and feed it to those GAN. But anime sketch colorization is very challenging and the whole community are looking forward to a solution. ALL current GANs are NOT good enough for anime sketch. But if you use landscape or anime faces, all current GANs are good.

**Comment by lgcagithub** [comment]
OK, thanks. :)
