### ISSUE TITLE
Input size vs. Output size

### ISSUE THREAD

**Issue by Ur-Procyon** [lllyasviel/style2paints#33]
This is a dream come true for me, as I wanted something like this for years. Thank you so much.

From what I have done with it so far, it seems that the output image is dependent on my monitor resolution. Is there any way to make the output image the same size as the input image? (I wonder if the program automatically downsizes the input image.)

Thank you for reading my post.

**Comment by lllyasviel** [comment]
There is a button "download result" below the "colorize".
Currently the resolution is limited to 512p (at max 1680*512) because of technique limitation.

**Comment by Ur-Procyon** [comment]
I see. And that max resolution can only be achieved with the downloaded program, not with the online version, correct?
