### ISSUE TITLE
Got Segmentation fault

### ISSUE THREAD

**Issue by ssshooter** [lllyasviel/style2paints#34]
![image](https://user-images.githubusercontent.com/13051472/32977989-9cbf6b28-cc73-11e7-9d34-fd4b4685e2ec.png)

**Comment by ssshooter** [comment]
![image](https://user-images.githubusercontent.com/13051472/32977963-320b125a-cc73-11e7-964c-bc9d2f2d0b0c.png)
![image](https://user-images.githubusercontent.com/13051472/32977965-3b996ac4-cc73-11e7-8a2a-59eaffc84fc7.png)

**Comment by abbychau** [comment]
you should have put the models in this way
![image](https://user-images.githubusercontent.com/350283/32978546-6042afdc-cc7f-11e7-8c68-1527f7788c3a.png)

**Comment by ssshooter** [comment]
thanks !
ps. Segmentation fault caused by git-bash, using cmd and run successfully.
