### ISSUE TITLE
Using Docker

### ISSUE THREAD

**Issue by 5agado** [lllyasviel/style2paints#36]
For anyone interested in relying on Docker I found it pretty straightforward, so wanted to share my minimal setup. Let me know if you eventually fancy a pull-request with all the required resources.

The following is for CPU server, but can be easily adapted.

*Dockerfile*

```
FROM gcr.io/tensorflow/tensorflow:latest-gpu-py3
# FROM gcr.io/tensorflow/tensorflow:latest-py3

WORKDIR /style2paints

ADD . /style2paints

RUN chmod -R 777 /style2paints

RUN pip install --trusted-host pypi.python.org -r /style2paints/requirementsCPU.txt

RUN apt-get update && apt-get install -y \
	libsm6 \
	libxrender1 \
	libfontconfig1 \
	libxext6

# Optional. Start server automatically
# RUN cd python /style2paints/server # first move into directory, otherwise the code won't be able to find the models
# RUN python server.py -cpu
```

*requirements.txt*
```
tensorflow
# tensorflow_gpu
keras
chainer
cupy
bottle
gevent
h5py
opencv-python
```

## Instructions

Copy *Dockerfile* and *requirements.txt* inside the *style2paints* directory.
Make sure to have the models inside the *server* directory as required by the project.

From *style2paints* run

    docker build -t style2paint-cpu .                              # build docker image
    docker run -p 8000:8000 -it style2paint-cpu bash   # start container in interactive mode

From inside the container run (unless automatically started in *Dockerfile*)

    cd server    # first move into directory, otherwise the code won't be able to find the models
    python server.py -cpu    # start server in cpu mode

From the host machine go to http://localhost:8000/

**Comment by abdellbobo** [comment]
I think this is a great idea
