### ISSUE TITLE
Empty Graph Error

### ISSUE THREAD

**Issue by rahulbaburaj** [lllyasviel/style2paints#41]
raise RuntimeError('The Session graph is empty.  Add operations to the '
RuntimeError: The Session graph is empty.  Add operations to the graph before calling run

Also how do I train the graph. What is the algorithm used and is code for training provided in the repository?

**Comment by lllyasviel** [comment]
maybe your has not put models properly. A screenshot of your server's file structure can be of help.

**Comment by rahulbaburaj** [comment]
![server](https://user-images.githubusercontent.com/8917417/34436501-62dc5fb0-ecbc-11e7-9f1c-da6ff959d32e.png)

(first folder is empty)

**Comment by lllyasviel** [comment]
ok your structure is right. It is strange. More logs?

**Comment by rahulbaburaj** [comment]
Sorry. I didn't understand. Whats wrong?

**Comment by lllyasviel** [comment]
I mean copy your whole logs here and maybe I can help you.

**Comment by rahulbaburaj** [comment]
main folder
![main_folder](https://user-images.githubusercontent.com/8917417/34436624-7b1c426a-ecbd-11e7-9771-12877298ebaa.png)

client
![client](https://user-images.githubusercontent.com/8917417/34436626-7fadb782-ecbd-11e7-84e0-ba391d77872d.png)

tempfile
![tempfile](https://user-images.githubusercontent.com/8917417/34436628-854a0e02-ecbd-11e7-9e7b-6c1f4a5ab5e6.png)

valiox
![valiox](https://user-images.githubusercontent.com/8917417/34436629-891d10a6-ecbd-11e7-8145-0f9f6b021d6b.png)

**Comment by rahulbaburaj** [comment]
Well, I updated my keras and it worked.
