### ISSUE TITLE
when I click "release"， there is no response！

### ISSUE THREAD

**Issue by viekie** [lllyasviel/style2paints#42]
when I click "release"， there is no response！

**Comment by lllyasviel** [comment]
wait and github will response you

**Comment by viekie** [comment]
ohhhhh，noooo.  I tried once and once again, but still no desponse! I used chrome explorer! I realy can not find the reason!

**Comment by viekie** [comment]
could you directly show model files url?

**Comment by kj415j45** [comment]
@viekie ~~probably gfw~~ :upside_down: you'd better use some tools(

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 LG-F460 发送_
