### ISSUE TITLE
I love your site so much

### ISSUE THREAD

**Issue by diyseguy** [lllyasviel/style2paints#52]
please bring it back

**Comment by suzumiyasmith** [comment]
it seems that the app is down due to a bug.
I have tried myself (run `python server.py`) but find it would shut down when runing full load for a long time.

**Comment by lllyasviel** [comment]
Thank you and we will be back soon

**Comment by Saren-Arterius** [comment]
I have a Dockerfile that runs a cpu only server that works in every machine although being much slower. I don't know if the models can be redistributed because they are all right reserved and I can't download the models from google drive in Dockerfile that I have uploaded them to my own server.

**Comment by diyseguy** [comment]
I am so excited to be finally running your software locally!  While I wait for your server to be up!

Thank you!!

![image](https://user-images.githubusercontent.com/27981142/38401704-2b111336-390c-11e8-9d12-c6658047f799.png)

**Comment by KVRYSV** [comment]
Hi, I'm an artist very new to using SQL and Python (and probably the technical world in general) and I wanna know how to locally run the app. I've seen the instructions on the github page but it skips a lot of things and I can't understand it (╥﹏╥)

**Comment by suzumiyasmith** [comment]
@KVRYSV 
simply follow the procedure in readme
If you have any specific problem you can ask in stackoverflow or somewhere

**Comment by KVRYSV** [comment]
Dang it really be your own vrodies (╯︵╰,)

**Comment by diyseguy** [comment]
Ooh nooo please don't cry!  😿    
It took me a few struggles to get it all going.
I'm using Cygwin on Windows and it took me a few days to sort out all the requirements...
Especially since Cygwin did not like cv2!  But then I used PyCharm to import the requirements and it was happy.   The only thing is, the pen doesn't work.  Which, I wish it did.

Peace
![image](https://user-images.githubusercontent.com/27981142/38652384-987735ba-3dba-11e8-878a-782efb20d7fd.png)

**Comment by deeppomf** [comment]
@lllyasviel On a side note, did you delete your Reddit account? I sent you a PM, but I can't see your account profile anymore.
