### ISSUE TITLE
How does the increasing number of input channels help colorization?

### ISSUE THREAD

**Issue by DexHunter** [lllyasviel/style2paints#6]
I saw the code [there](https://github.com/lllyasviel/style2paints/blob/master/server/server.py#L102) and am wondering why 4 channels as input help to produce better results? Are there some references or support theory?

**Comment by lllyasviel** [comment]
because paintschainer have 4 channels for input.
btw issues will be cleared before we promote our model. so all issue closed.

**Comment by DexHunter** [comment]
You can close it. But still why 4 channel is better than 3 as input? Remains a mystery
