### ISSUE TITLE
New UI doesn't format properly on all devices

### ISSUE THREAD

**Issue by pokeball99** [lllyasviel/style2paints#64]
![](https://i.snag.gy/Wn79RG.jpg)

**Comment by lllyasviel** [comment]
we think it is not very meaningful to run it on smart phone or ipad.
for pc, it has been tested on 1366*768, 1920*1080 ans many wider screens.

**Comment by UglyHat** [comment]
1680*1050 looks bad

**Comment by lllyasviel** [comment]
emmmmm maybe u are right

**Comment by lllyasviel** [comment]
fixed
