### ISSUE TITLE
Tutorial on how it works

### ISSUE THREAD

**Issue by SelaO** [lllyasviel/style2paints#65]
Is there a tutorial or guide on how this works and how you developed it?

If not, I really think you should make one for beginners.

It's a neat project that can really motivate people to learn about ML.

**Comment by abbychau** [comment]
It work by Generative adversarial networks (GANs) where you can find numerous resources online.

However, GANs are notoriously difficult to train, especially for this large network; there exists hundreds of choices of existing NNs and parameters that may not be explained.

But in short, there are some well defined discriminators inside.
A model is trained by by a sketch set and a painted set. parts of results are generated by U-Nets.

It is not a trivial network but for a beginner.
You can take https://github.com/pfnet/PaintsChainer as a reference and it includes model training code inside for you to learn (a lot).
The network structure is different from style2paints though.

**Comment by SelaO** [comment]
Is there any course or tutorial that you can recommend?

**Comment by abbychau** [comment]
@SelaO You can starts from `how CNN works?` and then `how GAN works?` and then I suggest a little content of GAN from https://github.com/soumith/ganhacks for you to start. 

here is a full example of using DCGAN
https://github.com/jacobgil/keras-dcgan

but it is not enough for you to GAN some real Anime images.

`vgg`, `inception`, `resnet` are very good models to discriminate or classify images. You can have a try.
