### ISSUE TITLE
Can you share the details of this work?

### ISSUE THREAD

**Issue by wenhaozheng-nju** [lllyasviel/style2paints#66]
This is the wonderful work. However, the outputs of GAN is hard to control. Hence, I am curious about how to make the GAN ouput the expected results by a few anchor points. 

Thanks very much!

**Comment by SNSLogty** [comment]
The developer usually answer questions in his group.If you have a QQ account,you can join the QQ group and talk to the developer.you can click [this](https://jq.qq.com/?_wv=1027&k=5cnd54S) to join the group
