### ISSUE TITLE
Great Result. Great Project. Sharing my result.

### ISSUE THREAD

**Issue by shrekshao** [lllyasviel/style2paints#67]
Hi. I'm from zhihu. I tried this and paintschainer. And this paintsTransfer gives way better result. The accurate point feature is a killer. I cannot upload images at zhihu comment section so I come here to put an issue. I'm the author of the sketch so feel free to use for demonstrating and training purpose. 

As a spare time indie game developer I must say this has great potential. Content creation is a big bottleneck for today's game dev. Maybe consider to try [patreon](https://www.patreon.com/) or [kickstarter](https://www.kickstarter.com) or simply a donate account for community and income?

Again thank you for this great project.

![paintstransfer](https://user-images.githubusercontent.com/5031596/39737719-c62808aa-523b-11e8-99a2-134ab6c1c43d.png)

![paintschainer](https://user-images.githubusercontent.com/5031596/39737707-af734458-523b-11e8-9a61-670cca273a6d.png)

**Comment by SNSLogty** [comment]
If you have a QQ account,you can join the QQ group and talk to the developer.The QQ group number was in the markdown.
or you can click this [the links](https://jq.qq.com/?_wv=1027&k=5cnd54S)
