### ISSUE TITLE
How to download middle picture?

### ISSUE THREAD

**Issue by diyseguy** [lllyasviel/style2paints#68]
Hello,

I like your program a lot.  However, I'm confused by the middle image.  It often looks quite different than the result.  Oftentimes, I like the middle one better, but cannot download it, e.g.

![image](https://user-images.githubusercontent.com/27981142/39961581-4d3c133a-55ee-11e8-959f-5c0e908cf02e.png)

**Comment by abbychau** [comment]
They are respectively `sketch.*.jpg`, `composition.*.jpg`, `result.*.jpg` of the current version.

You can download it by simply replace `result` with `composition` in your address bar while downloading the result.
