### ISSUE TITLE
We are collecting failure here.

### ISSUE THREAD

**Issue by lllyasviel** [lllyasviel/style2paints#7]
If you find a colorization failure, please upload the sketch and your reference image here in reply.

**Comment by DexHunter** [comment]
I was trying to colorize some of my images. (from both sketchKeras and handrawn) Although the outline is preserved, the colorization does not seem right to me.
![failed](https://user-images.githubusercontent.com/6930518/29876265-dd050eec-8dce-11e7-905a-401f836989b8.png)
![failed2](https://user-images.githubusercontent.com/6930518/29876532-a95cf676-8dcf-11e7-9d38-79fd3b93bbb7.png)
![failed3](https://user-images.githubusercontent.com/6930518/29876541-af08d068-8dcf-11e7-836a-5830ce7749fa.png)

**Comment by lllyasviel** [comment]
checked.

**Comment by DexHunter** [comment]
Hi again! I think the network is decent enough but there are still space left for improvement.
![failed4](https://user-images.githubusercontent.com/6930518/29970559-b234e586-8f57-11e7-8ee0-c7002c9c565c.png)

For this image, the part below face is not colored
![failed5](https://user-images.githubusercontent.com/6930518/29970580-c3384d64-8f57-11e7-818e-ceba0a3b8731.png)
And this when reference is really colorful, the network seems to be intimidated to use all the color.

The reference image is this:
![b9fhr91ceaamtve](https://user-images.githubusercontent.com/6930518/29970681-0e1909a4-8f58-11e7-9902-2c7096a5ee12.jpg)

(all images from Internet)


So I was wondering if there is a guideline for sketch & reference? Besides, it seems that there is a limit for sketch size and limit for ratio between sketch&reference (e.g. if reference Height>Width then sketch needs to Height>Width as well)

**Comment by lllyasviel** [comment]
Yes there should be a guideline for sketch & reference.
Maybe I will write a github.io page to describe the model's preference when our final model is finished.

**Comment by lllyasviel** [comment]
But before I write a guideline, I have to work out the network's perference.
In fact I also do not know what my model likes and dislikes.

**Comment by wchristian** [comment]
It seems to be intent on coloring faces with "white skin color" even if the reference doesn't contain that color.

![screenshot 2017-09-29 12 25 18](https://user-images.githubusercontent.com/175467/31045338-de2dd396-a5e1-11e7-99d5-c1ff4401818f.png)
![screenshot 2017-09-29 21 11 18](https://user-images.githubusercontent.com/175467/31045341-e9724fac-a5e1-11e7-884b-7d15e36c31d5.png)

**Comment by lllyasviel** [comment]
@wchristian 
First of all, I am scared by your so mannnnnnny tabs in your browser :p
Then maybe I can add some related datasets to tune this kind of results? hmmmmmmm...

**Comment by wchristian** [comment]
That's my browser with the small amount of tabs! :D

As for dataset, not entirely sure how this works, but i am guessing the training set contains only default white-skinned characters, so the NN doesn't know to expect that characters can have different skin colors? Maybe adding various other examples from various tags here might help? http://danbooru.donmai.us/tags?commit=Search&search%5Bhide_empty%5D=yes&search%5Bname_matches%5D=%2A_skin&search%5Border%5D=count&utf8=%E2%9C%93

I also just recently learned about the color hinting tool, and tried to get the tiger above grey-skinned. Ended up having to basically paint the entire face because the NN insisted that a face should have skin color. :)

**Comment by lllyasviel** [comment]
@wchristian Oh thank you. I will try to improve it.
