### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by abdellbobo** [lllyasviel/style2paints#71]
can use it offline mode without internet or servers?

**Comment by liujiacode** [comment]
Of course you can use it offline, but you have to launch the local web server first. Just follow the steps in https://github.com/lllyasviel/style2paints#launch-server and run "python server.py" to start the web app server. Then, open "http://127.0.0.1:8000/" in your web browser and you will see the interface of PaintsTransfer.

**Comment by SNSLogty** [comment]
We have made a offline program and it is easy to use .
you just need download the files and click the bat.Then , open "http://127.0.0.1:8000/" in your web browser and you will see the interface of PaintsTransfer.
download link [https://pan.baidu.com/s/1x5dSFjTT9OkARhbIupSKxQ](url)
download password: 2333

**Comment by abdellbobo** [comment]
@SNSLogty I did what you told me but I get this error :
https://pastebin.com/z5WxEgRA
any ideas for fixing it thank you very much.

**Comment by SNSLogty** [comment]
@abdellbobo 
Does your computer have 6GB+ RAM ?
This program need 6GB or more RAM to initialize,you also need a powerful CPU to let the program color illustrations
if you want to use it,we have a temporary mirror website [http://47.75.12.29/](url)

**Comment by abdellbobo** [comment]
@SNSLogty thank you very much your solution is amazing and yes  I have a gaming computer using Nvidia Cuda GPU 16GB of RAM.
I finally fixed my problem checking the two boxes and download the other programs from Visual Studio.
https://imgur.com/a/G9buiyG

**Comment by RubiscoF** [comment]
Thanks for your email. Because there are some annoying things, I haven't use your cute program. So I want to ask you that if I could use it to color compartment comic? Just like a Marvel comic?

SNSLogty <notifications@github.com>编写：



I am glad to hear that.If you have any feedback about this offline program,please talk to me.

―

**Comment by SNSLogty** [comment]
@RubiscoF Yes,see this [video](https://www.bilibili.com/video/av23686807)

**Comment by abdellbobo** [comment]
@SNSLogty is it normal that offline mode use a lot of your CPU and just 20% from your GPU ?

**Comment by SNSLogty** [comment]
@abdellbobo 
My offline program only use CPU to color,not use the GPU of your computer.
gpu mode need use pip  install tensorflow_gpu

**Comment by KumoKyaku** [comment]
还有其他下载连接么，公司不能用百度客户端，没有客户端下载不了大文件

**Comment by SNSLogty** [comment]
@KumoKyaku 对于中国用户，我们写了一个中文一键版[https://github.com/SNSLogty/style2paints-offline](https://github.com/SNSLogty/style2paints-offline)

**Comment by schenad** [comment]
![1](https://user-images.githubusercontent.com/24725023/45061887-04e6ef00-b06c-11e8-836b-6b79ccc3779e.png)
![2](https://user-images.githubusercontent.com/24725023/45061888-04e6ef00-b06c-11e8-8206-cc5de44e3dce.png)
One of my friend tried @SNSLogty 's program in pan.baidu.com, and got the above information. Any suggestion for him? It seems like the problem is from TensorFlow, and I am not sure if I should let him just re-install the TensorFlow in that folder (which I don't know how to do) or just teach him to install the whole python environment under Anaconda (which was what I did, but quite tedious).

**Comment by SNSLogty** [comment]
@schenad 
Have yoou ever installed VC2010/VC2015 ?

**Comment by schenad** [comment]
@SNSLogty He said no.

**Comment by SNSLogty** [comment]
@schenad 
Download the  [Microsoft Visual C++  Redistributable Package ](https://cn.bing.com/search?q=Microsoft%20Visual%20C%2B%2B%20%20Redistributable%20Package%20&qs=n&form=QBRE&sp=-1&pq=microsoft%20visual%20c%2B%2B%20redistributable%20package%20&sc=2-45&sk=&cvid=9895B879AC5140F4A90184863D3ECA2D) and install them.
I am not sure about this error,But someone solved it by install the Microsoft Visual C++  Redistributable Package.You can try to install the 2010/2013/2015 version and then restart my program

**Comment by schenad** [comment]
@SNSLogty Thank you very much!

**Comment by YukiSakuma** [comment]
@SNSLogty First of all thanks for this amazing program, I have no problem running the offline version but I need to use my GPU in processing because my CPU is always crying, is there an instruction for this offline version to make use of the GPU?

**Comment by SNSLogty** [comment]
@YukiSakuma 
Here is the way to install the GPU mode https://github.com/lllyasviel/style2paints/tree/master/V3#Launch%20Server
GTX980 may not support :( ,We suggest GTX1060 6GB to run the mode.

**Comment by IKAR0S** [comment]
@SNSLogty nothing happens when i clic ctrl-c
[https://imgur.com/a/8BOdMGY](url)

**Comment by Superkenthor** [comment]
@SNSLogty I'm having the exact same problem as @IKAR0S. It keeps giving me the wrong site to visit for the local server and the ctrl-c doesn't do anything.

**Comment by SNSLogty** [comment]
@IKAR0S 
@Superkenthor 
if you hit Ctrl-c,you will shu down the server.you just need to open 127.0.0.1:8000 when the server is ready.If you can't open the web page,try to clean up the cache of you browser.

**Comment by SNSLogty** [comment]
https://github.com/SNSLogty/style2paints_v3_launcher/blob/master/1.png
https://github.com/SNSLogty/style2paints_v3_launcher/blob/master/2.png
https://github.com/SNSLogty/style2paints_v3_launcher/blob/master/3.png
@IKAR0S
@Superkenthor

**Comment by IKAR0S** [comment]
@SNSLogty thanks!
It is possible to add Danbooru2017 dataset to this offline program? If it is possible how can i implement it?
