### ISSUE TITLE
http://paintstransfer.com/ timing out

### ISSUE THREAD

**Issue by Mal1t1a** [lllyasviel/style2paints#72]
Hi,

The website is not allowing me to connect. I keep getting a timeout response in chrome: ERR_CONNECTION_TIMED_OUT

**Comment by abdellbobo** [comment]
on the README.md

`http://paintstransfer.com
`
is out of service(Because some financial problems, our online app is shut down temporarily.)

**Comment by SNSLogty** [comment]
@Mal1t1a 
if you want to use it online,we have a temporary mirror website http://47.75.12.29/

**Comment by goyzhang** [comment]
@SNSLogty 
This looks like a nice project. About the financial problems, is there any way we can donate?
