### ISSUE TITLE
OSError: Unable to open file (unable to open file: name = 'baby.net',

### ISSUE THREAD

**Issue by anymoreT** [lllyasviel/style2paints#74]
When I run python server.py,  it prompt error message: 
OSError: Unable to open file (unable to open file: name = 'baby.net', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Who can tell me how to handle this problem?  the network baby.net is broken?

**Comment by abbychau** [comment]
Please read the readme:

https://drive.google.com/open?id=1fWi4wmNj-xr-nCzuWMsN2rcm0249_Aem
