### ISSUE TITLE
[Edited] Pay extra attention to the CUDA version

### ISSUE THREAD

**Issue by bimOvO** [lllyasviel/style2paints#75]
*Sorry for the last wrong issue I've committed.*
Reason is that I didn't realize CUDA 9.2 doesn't will to work with tensorflow_gpu 1.8.0. So either to use CUDA **9.0** or install the modified version that works with CUDA 9.2.
By the way, this project is quite **PERFECT** ! We like it very much! Thanks a lot!

**Comment by abdellbobo** [comment]
@bimOvO can you tell me how you installed tensorflow as a basic module ?

**Comment by bimOvO** [comment]
@abdellbobo I don't know if my expressions are correct, but I means run `pip install tensorflow` before `python server.py` , otherwise an error would be occurred when importing "tensorflow". (*ai.py, line 1*)
![image](https://user-images.githubusercontent.com/20502130/42405276-b4d01cfa-81c5-11e8-91e1-72b500952b64.png)
