### ISSUE TITLE
OP_REQUIRES failed at random_op.cc:202

### ISSUE THREAD

**Issue by ouyangbei** [lllyasviel/style2paints#76]
Can you tell me what's the problem "OP_REQUIRES failed at random_op.cc:202 Resource exhausted:OOM when allocating tensor with shape[576,864] and type float on /job/localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc", and how to fixed it

**Comment by abbychau** [comment]
exhausted:OOM means that your display card does not have enough memory.
what card are u using?

**Comment by cppietime** [comment]
I'm having a similar problem with my GeForce 750 Ti

**Comment by abbychau** [comment]
I am not sure if the 4GB version could work, but the 2GB version MUST cause am OOM. I recommend 6GB+ display cards.

**Comment by passerby233** [comment]
I got the same problem with my 2GB card but I solved the problem by running in CPU mode. If you have installed the tensorflow-gpu, it is defaulted to use all the GPU. So just add a piece of code like the following on the top of the "server.py"  will shift to the CPU mode.

import os
os.environ["CUDA_VISIBLE_DEVICES"]="-1"

The code means no visible CUDA_DEVICES for the program and tensorflow will shift to the CPU automatically.
---------------------------------------------------------------------------------------------------------
对于使用内存2GB的NVIDIA显卡并安装了tensorflow-gpu的用户，在server.py文件头部添加
import os
os.environ["CUDA_VISIBLE_DEVICES"]="-1"
可以转化为CPU运行模式。
