### ISSUE TITLE
Running on cpu

### ISSUE THREAD

**Issue by Sebastian-Panula** [lllyasviel/style2paints#83]
Hi can this be used on only cpu, I have amd gpu so no luck there.

**Comment by abdellbobo** [comment]
yes u can

**Comment by Sebastian-Panula** [comment]
Yes i tried using the -cpu but errors from missing dll

**Comment by pelya** [comment]
Install tensorflow instead of tensorflow_gpu

**Comment by Sebastian-Panula** [comment]
I used tensorflow instead of tensorflow_gpu.
This project doesn't have much information about running offline.
