### ISSUE TITLE
Error 403 Forbidden when running local server v3

### ISSUE THREAD

**Issue by TheIvanic** [lllyasviel/style2paints#84]
I'm trying to run a local server, but once it's up and running any attempt to connect results in an error 403 forbidden with the message "Access Denied"  Here's a pastebin link to my console log: https://pastebin.com/E2K0btfv

**Comment by abdellbobo** [comment]
ignore the message and go to your browser and type
http://0.0.0.0:80/

**Comment by TheIvanic** [comment]
Connecting to 0.0.0.0:80 doesn't work, and nothing shows up in the console when I do so.

**Comment by MattJTrueblood** [comment]
might be a windows firewall issue.  Try disabling that.

**Comment by TheIvanic** [comment]
Nope, no change with firewall disabled.

**Comment by trufty** [comment]
Windows 10, this worked for me:
In server.py change: 
`static_file("index.html", root='game/')`
To:
`static_file("index.html", root='./game')`

**Comment by TheIvanic** [comment]
This solved it, though I also changed one other instance of root='game/' to root='./game'.  Not sure if that was necessary but doesn't seem to have hurt.  Anyways, thanks for the help everyone.
