### ISSUE TITLE
[Suggestion] make option to keep alpha channel surrounding image upon download

### ISSUE THREAD

**Issue by xtrap01nt** [lllyasviel/style2paints#86]
This is definitely something that could be done in photoshop after downloading the file, but if there was an option to have plain backgrounds turn into alpha channel it would make for a smoother workflow going from the app to an image editor.

**Comment by SylveonBottle** [comment]
Maybe we could have a 'color' that has the ai paint in.. transparency?

**Comment by SylveonBottle** [comment]
Could we get information on this? Has it been added already?

**Comment by lllyasviel** [comment]
SEPA will have an AI-driven matting system to independently resolve all alpha problems.
