### ISSUE TITLE
Update repo with V4 source

### ISSUE THREAD

**Issue by MattJTrueblood** [lllyasviel/style2paints#87]
https://s2p.moe/ seems to be running a later version of the codebase (v4?) than the current latest committed source, which is in the v3 folder.

Will the new version be available soon?

**Comment by SNSLogty** [comment]
The developer is busy creating the offline verison of V4(_Powered by Unity_),The offline Web-app of V4 has too much bug. 
@SylveonBottle You can try to refresh the website crazily to get in(I refresh it 10 times and succeed)

**Comment by brianlin1992** [comment]
> Please! This tool is so amazing, it's a horrible shame that we have to constantly refresh for so long just to get a shot at using it..!

Why shame? the developer has been trying their best to deliver a good and open-source tool. Better to show more respect and thankful, especially it's still in developing stage.

**Comment by SylveonBottle** [comment]
> > Please! This tool is so amazing, it's a horrible shame that we have to constantly refresh for so long just to get a shot at using it..!
> 
> Why shame? the developer has been trying their best to deliver a good and open-source tool. Better to show more respect and thankful, especially it's still in developing stage.

This tool is so amazing, I'm really grateful for the developer to be providing this tool open-source. It's just a shame that I can't use it!

**Comment by marcussacana** [comment]
And what the point to use a repositorie to just publish the final version?
If is to this it's better host a blogpost or wordpreess and upload in a random host.

We requested but we know he is currently in dev stage, but it's usable, rigth? if isn't the case he don't did the v4 server public.

And


> Why shame? the developer has been trying their best to deliver a good and open-source tool. Better to show more respect and thankful, especially it's still in developing stage.

Everyone know and is thankful for the software, but he just requested a feature, I do not see any lack of respect in that.

If the creator isn't open to accept request o feedbacks, he would have blocked issues creation... Or Is what I think... well, he is using the github as final release platform after all...

I think if he don't want make public for bug reasons, just create a new branch and push to him, no reason don't publish, of course, I'm not saying he have that he has an obligation to publish.

**Comment by lllyasviel** [comment]
Hi, all. We will upload all our codes of V4 after our paper, including server, client and some other small tools, e.g. chrome helper and so on. If we upload our code right now, the academic community of the related technologies will be in chaos. We need some formal documents for reference and citations.

**Comment by MattJTrueblood** [comment]
Sounds good.  Looking forward to it

**Comment by cuitianxiang100** [comment]
What an amazing tool it is, I looking forward to it.In spirit I was with you here.

**Comment by Oskop** [comment]
Thanks For your effort. I'll be waiting for the paper too.

**Comment by Vadimak170** [comment]
> Hi, all. We will upload all our codes of V4, including server, client and some other small tools, e.g. chrome helper and so on, after the publication of our paper. If we upload our code right now, the academic community of the related technologies will be in chaos. We need some formal documents for reference and citations.

I love what you have created. This is really great and impresses me. Please do not stop doing what you do. Good luck to you!

**Comment by JohnWang1023** [comment]
Any updates ?

**Comment by marcussacana** [comment]
No source but a offline build is already avaliabe

**Comment by JohnWang1023** [comment]
> No source but a offline build is already avaliabe

I see, but the offline build is only available for windows.

**Comment by marcussacana** [comment]
At least with me, I managed to run in the WINE, You just need install the Cuda drivers and use the wine-devel branch
