### ISSUE TITLE
Feature request: Docker image

### ISSUE THREAD

**Issue by whalehub** [lllyasviel/style2paints#89]
It would be awesome if you could create an official Docker image for style2paints and push it to the Docker Hub. It would allow people to easily self-host this software on their own server. You could use the Dockerfile from [this issue](https://github.com/lllyasviel/style2paints/issues/36) as a starting point. It would be ideal if you used [automated builds](https://docs.docker.com/docker-hub/builds/) so that you don't have to manually push the image every time you make a change.

**Comment by 5agado** [comment]
Notice that the referenced one relates to an old version. I made a updated one for the newest version, but need to polish before posting it. Also some stuff I didn't automate, like models download.
Not sure overall where the authors stands regarding the dockerization.
