### ISSUE TITLE
Suggest to auto lower midtone for inputs

### ISSUE THREAD

**Issue by abbychau** [lllyasviel/style2paints#9]
by using the following sketch and reference:
![sep19_03120010262 sketch](https://user-images.githubusercontent.com/350283/30559818-8a2e9f02-9ce8-11e7-9607-86a9bbb58fef.png)

![sep19_03120010262 reference](https://user-images.githubusercontent.com/350283/30559821-8f1eaaca-9ce8-11e7-937d-d8afb0fd11d1.png)

will result in this image:

![sep19_03120010262 fin](https://user-images.githubusercontent.com/350283/30559833-970c81c6-9ce8-11e7-8a77-8663b9164490.png)

which does not seem bad but it is seeming to be limited by the certainty level of the sketch input due to the low contrast/blackness of the sketch.

This is the grayscale input used:

![sep19_02025290662 sketch_greyscale](https://user-images.githubusercontent.com/350283/30559640-dfbddf60-9ce7-11e7-866a-b1b6f58ec586.png)

Actually we can simply lower down the midtone to give more global hint with scarifying very minor local details.
![sep19_02025290662 sketch_greyscale_midtone](https://user-images.githubusercontent.com/350283/30559667-fcbec980-9ce7-11e7-9420-469f7d77c216.png)

The result could be better:
![sep19_03113994174 fin](https://user-images.githubusercontent.com/350283/30559980-03fae4da-9ce9-11e7-810f-98eb24b88d39.png)

Midtone suppressing could work in any original input that is already with quite good clairty as well.

It can seldom be harmful for a sketch:
![587321_orig](https://user-images.githubusercontent.com/350283/30560161-96b90a7c-9ce9-11e7-8ec9-f7ef373f5127.jpg)
![587321_origmid](https://user-images.githubusercontent.com/350283/30560162-96c552b4-9ce9-11e7-8641-288a46752247.jpg)

.

**Comment by lllyasviel** [comment]
![image](https://user-images.githubusercontent.com/19834515/30576783-b79221e0-9d3c-11e7-9ca5-d5664018c1e3.png)
![image](https://user-images.githubusercontent.com/19834515/30576805-ee854074-9d3c-11e7-8637-999e26e027d6.png)

Merged
