### ISSUE TITLE
Color may "leak" when coloring eyes（在给眼睛上色的时候，眼角有可能跟眼睛同色）

### ISSUE THREAD

**Issue by Neutron3529** [lllyasviel/style2paints#91]
为了符合github的习惯先写一段英文，详细的故事（以及一点不知是否正确的修改想法）会用中文写在最后
![default](https://user-images.githubusercontent.com/26130174/48970580-c0eeff00-f048-11e8-84b7-631682e6919b.png)
as you can see, this graph contains some noise, so firstly I use careless mode to coloring it.
![gal1](https://user-images.githubusercontent.com/26130174/48970651-ea5c5a80-f049-11e8-8be2-99e1ed3643e3.png)
I set two blue point to this graph and set some color point (near white) surronding the eye, but when style2paints finish coloring, some blue color seems leak outside the eye.
this leak will also appear when using careful mode
![yuv h00m20s41](https://user-images.githubusercontent.com/26130174/48970689-5b037700-f04a-11e8-83f3-6180507bdf69.jpg)

It may due to the noisy lines which cause this situation.

在处理这张画像的时候，我首先选择的是careless模式，发现我们赋给眼珠子的蓝色会漏出眼珠子
后来我换了careful模式检查了一下，仔细观察careful模式下的图案，可以看出careful似乎的确识别出了眼睛（上下眼睑都很醒目）但是的确有一块皮肤变成了蓝色。
（Example 7里面眼珠子跟皮肤的分界似乎也是渐变的而没有一个明显的轮廓）

或许在指定上色的时候应该预先用一下人脸识别之类的技巧计算颜色影响的区域（比如蓝眼珠子就是蓝眼珠子，不能影响到眼皮……）
或许可以根据人类的识别物体的精度对各种区域进行一些限制
（当然，我在这里动嘴皮子的代价很可能是写代码的你们用几周+几百行代码+几万个测试集才能搞定的东西）
或许还有一点，虽然强行加光照很好看也（比如光照可以去掉许多上色的缺陷）
但是光照实在太容易被解释成纸张的褶皱了
（这段评论是看见Example里面那只猫才加上去的，因为使用光照渲染之后，图像真的会变得很好看，有一种被熊孩子折皱了然后展开之后赶快拿摄像机拍照保护的感觉（……））
![gal-rl](https://user-images.githubusercontent.com/26130174/48970848-6d7eb000-f04c-11e8-9922-3600e6a9a525.jpg)

Anyway, thank you.

**Comment by lllyasviel** [comment]
OK. This image is very challenging for most colorization bots, even in 2018. 

However, the powerful style2paints can still give you sth useful, if used properly. The trick is very simple: open your flatten mode, and select the first result after you download the image.

You will get something like:

![composition h03m05s05](https://user-images.githubusercontent.com/19834515/48972156-eb988200-f05f-11e8-8bbe-ccf9d8778728.jpg)
![composition h03m05s38](https://user-images.githubusercontent.com/19834515/48972157-eb988200-f05f-11e8-8699-1618e673c08a.jpg)
![composition h03m05s55](https://user-images.githubusercontent.com/19834515/48972158-ec311880-f05f-11e8-8c14-ed586425121d.jpg)
![composition h03m06s30](https://user-images.githubusercontent.com/19834515/48972159-ec311880-f05f-11e8-8ffa-0ca307eba70e.jpg)
![composition h03m06s47](https://user-images.githubusercontent.com/19834515/48972160-ec311880-f05f-11e8-99b4-933483c933fe.jpg)
![composition h03m08s25](https://user-images.githubusercontent.com/19834515/48972161-ecc9af00-f05f-11e8-8c66-853038423c14.jpg)

You can create fine colored arts, with these image and your original inputs in PS. Or you can directly use style2paints results. These are just fine imo.

PS: currently the rendering system will be disturbed by noises. Then just give up the renderer.
