### ISSUE TITLE
ImportError: No module named 'paste'

### ISSUE THREAD

**Issue by genshishio48** [lllyasviel/style2paints#92]
When i run the 开始.bat to open server.py
i don't know what's wrong

D:\style2paints\server>..\python\python.exe server.py
Using TensorFlow backend.
D:\style2paints\python\lib\site-packages\keras\engine\saving.py:270: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
Bottle v0.12.13 server starting up (using PasteServer())...
Listening on http://0.0.0.0:80/
Hit Ctrl-C to quit.

Traceback (most recent call last):
  File "server.py", line 267, in <module>
    run(host="0.0.0.0", port=80, server='paste')
  File "D:\style2paints\python\lib\site-packages\bottle.py", line 3127, in run
    server.run(app)
  File "D:\style2paints\python\lib\site-packages\bottle.py", line 2818, in run
    from paste import httpserver
ImportError: No module named 'paste'

**Comment by SNSLogty** [comment]
Maybe you are using the latest code of V3.
**method 1:**
open the cmd and input:
`pip install paste `
**method 2:**
Use the Easy_Pack 
look #71 and here is the [downlod link](https://github.com/lllyasviel/style2paints/issues/71#issuecomment-398694715)

**Comment by genshishio48** [comment]
for method 1, is that a linux command ?
for method 2, i've download it and that's why i ask above

**Comment by genshishio48** [comment]
> Maybe you are using the latest code of V3.
> **method 1:**
> open the cmd and input:
> `pip install paste `
> **method 2:**
> Use the Easy_Pack
> look #71 and here is the [downlod link](https://github.com/lllyasviel/style2paints/issues/71#issuecomment-398694715)

for method 1, is that a linux command ?
for method 2, i've download it and that's why i ask above

**Comment by SNSLogty** [comment]
@genshishio48 What is your system? Linux or Windows

**Comment by genshishio48** [comment]
I fixed it by installing this module https://github.com/cdent/paste
my problem is solved

**Comment by carroz** [comment]
@genshishio48 hey, how did you do this? using pip install paste did not work for me

**Comment by PurushothamanSrikanth** [comment]
> > Maybe you are using the latest code of V3.
> > **method 1:**
> > open the cmd and input:
> > `pip install paste `
> > **method 2:**
> > Use the Easy_Pack
> > look #71 and here is the [downlod link](https://github.com/lllyasviel/style2paints/issues/71#issuecomment-398694715)
> 
> for method 1, is that a linux command ?
> for method 2, i've download it and that's why i ask above

@niizam method 1: This command is used to install Packages (here Python Packages) from The Python Package Index (PyPI)[](https://pypi.org/). It works on Linux and Windows both.
