### ISSUE TITLE
Online app issue

### ISSUE THREAD

**Issue by IKAR0S** [lllyasviel/style2paints#96]
I have tried multiple times, but always getting the same error: "Network Error. Please refresh this page."
![image](https://user-images.githubusercontent.com/44556469/50736519-c9e1fd00-11be-11e9-9c69-184243037a48.png)

**Comment by stefnotch** [comment]
Try disabling all your extensions and see if the issue persists.

**Comment by IKAR0S** [comment]
@stefnotch same
![image 1](https://user-images.githubusercontent.com/44556469/50736799-14b14400-11c2-11e9-914e-3a9d12c212c0.png)
