### ISSUE TITLE
Source code offline?

### ISSUE THREAD

**Issue by BlohoJo** [lllyasviel/style2paints#97]
Confused why the source code has been taken offline... I understand server maintenance and such, but not understanding why code was pulled?

**Comment by SNSLogty** [comment]
https://github.com/lllyasviel/style2paints/issues/87#issuecomment-441222893

> Hi, all. We will upload all our codes of V4, including server, client and some other small tools, e.g. chrome helper and so on, after the publication of our paper. If we upload our code right now, the academic community of the related technologies will be in chaos. We need some formal documents for reference and citations.

**Comment by BlohoJo** [comment]
That makes things less confusing, thank you!

**Comment by Ben76904** [comment]
Hello, all! I would like to first say I really love and enjoy using this program. I downloaded the program file here but I have no idea how to use it. Can anyone tell me the first step in running or opening this program on my computer? Any info would be great!

**Comment by Ben76904** [comment]
Hello, all! I would like to first say I really love and enjoy using this program. I downloaded the program file here but I have no idea how to run or open this program on my computer? Can someone give me the first steps? Any info would be great!

**Comment by stefnotch** [comment]
@Ben76904 So far, you can't run V4 of the program. V3 might work and the instructions for it are here:

https://github.com/lllyasviel/style2paints/tree/master/V3#launch-server

**Comment by Ben76904** [comment]
@stefnotch Thanks for the info! I'm familiar with the instructions and use of the program. My struggle is opening V4 or V3 on my Desktop. (I see V4 is down atm) Do I need additional software to open V3 like "GitHub Desktop" or "Visual Studio" for example? I'm absolutely new to Github but learn quickly. Thanks again!

**Comment by onsoho** [comment]
> @stefnotch Thanks for the info! I'm familiar with the instructions and use of the program. My struggle is opening V4 or V3 on my Desktop. (I see V4 is down atm) Do I need additional software to open V3 like "GitHub Desktop" or "Visual Studio" for example? I'm absolutely new to Github but learn quickly. Thanks again!

hello, I'm going to assist you, give me a few minutes.

**Comment by onsoho** [comment]
@stefnotch Are you using CPU or GPU?

**Comment by stefnotch** [comment]
> *you need a python 3.5/3.6 GPU environment with cuda.*
-- [Instructions](https://github.com/lllyasviel/style2paints/tree/master/V3#launch-server)

Though, I personally have never tried to run it.

**Comment by onsoho** [comment]
@stefnotch Right, you can run V3 using your CPU or GPU, is optional the GPU but I recommend a lot because is more faster. Anyway, first you can try using your CPU.

**Comment by onsoho** [comment]
If someone want run this on CPU this the way:

Install 2010/2013/2015 versions: [Microsoft Visual C++ Redistributable Package](https://www.bing.com/search?q=Microsoft%20Visual%20C%2B%2B%20%20Redistributable%20Package%20&qs=n&form=QBRE&sp=-1&pq=microsoft%20visual%20c%2B%2B%20redistributable%20package%20&sc=2-45&sk=&cvid=9895B879AC5140F4A90184863D3ECA2D&mkt=zh-CN)

Install "Tensorflow" for cpu using in python: pip install tensorflow
(don't install "tensorfow-gpu")

# Launch Server

Run : python server.py -cpu

Open your browser using this address: '127.0.0.1:80' or 'localhost'

**Comment by Ben76904** [comment]
@onsoho. Thank you. Will try!

**Comment by onsoho** [comment]
Let me now if you have some issues like "ImportError: DLL load failed", are very common.

**Comment by BradleyDS2** [comment]
@mosheliv Are you seriously suggesting that because he never stated the words "I promise" it means he never broke his word?


What kind of mental gymnastics classes are you taking?

**Comment by mosheliv** [comment]
Definetly not one in your gym, which is a much higher level. People like
you make open source developers a bit noxious.

Anyways, I'll let you have the last word, as I am not going to comment on
this anymore.

**Comment by BlohoJo** [comment]
The point is, if you needed more money for the server, then you should have simply stated that from the start. Saying the server is coming back on a given date, then NOT bringing it back on that date, shows that your word can't be completely trusted. Now it is harder for people to trust you when you ask for donations.

**Comment by mosheliv** [comment]
Sigh, see? I promised not to respond and i am already breaking my promise!
Btw, disclaimer: i am not related in anyway to these people. Actually I am
not even using this software.
So, back to our fascinating argument :
1. S&#t happens. Maybe he go married and found out a house he can't afford
while paying 12000$ a year for your pleasure? Maybe his mother suddenly
needs urgent medical procedure and forgot to renew her insurance? Why are
you so hard?
2. So, about your "logic"... It would be ok if he brought the server up for
a day and then shut it down? No promise broken, right?

Meh, i won't say i am not going to respond. I am enjoying this far too
much.

**Comment by mosheliv** [comment]
Also, wanted to give a capitalistic argument as altruism and compassion
don't seem to be your strong point :

What exactly did you think your post is going to achieve? Let's look at the
different outcomes. I seriously doubt he is going to say to himself "Oh! He
is right! I broke my promise! How stupid of me! I didn't notice! Where is
my credit card? I am going to put the site up right away!", so this is
really low probability.
Now, if you actually wanted the site up, your post discourage people from
donating. Keeping your mouth shut would actually work better for you. So,
the only logical deduction is that you want the site down. Hmmmm very
strange.

**Comment by SNSLogty** [comment]
@BlohoJo  The developer is just a college student.And he doesn't have a stable income.So it is hard to afford this costly server.The reason why he only open the version 3 is because he could maintain his right by the paper(his v2 was stolen by a company，and this company used it to cheat a huge investment).The developer will open v4 offline until he fininsh the paper.He just need money to establish the online v4.And he would not stop developing because of the money.
So please wait for it patiently

**Comment by BlohoJo** [comment]
I understand and that is all good. But you (he) needs to be careful about making declarations and then not delivering on them. I've seen this happen too many times to too many amateurs and professionals over the last 20 years, both for free and commercial projects.

Just say only what you know for certain. Don't give a date until you are certain. Don't say if you get X amount of dollars then Y will happen, unless you are 100% certain.

If you are "pretty sure" or "plan to" have X happen by a deadline, then don't announce it as a certainty, because if it doesn't happen, you hurt the reliability and credibility of your word, and there is a big cost for that, even if what you are developing is free. In this case, he is a college student working on a paper for this project. Given what he was able to accomplish, this has the potential to give him great success for the future, but he hurts that if he goes back on his word in a public way like this. He already got hurt by people taking advantage of him... he doesn't need to add to that!

**Comment by lllyasviel** [comment]
OK. In fact the story is: Before 2018.01.20, we have a sponsor, namely A. A gives us some money for the server every month. Though we have a donation site, we still need his money because the current donation can only cover a small part of the server. A told me that the money will be available before 2018.01.27, so I said the server will come back at 27. Finally, A failed in giving money and we have to close the server.

As to the donation, we have two choices: shut down the donation site or not. I think closing the donation will sounds like someone quit a game emptying project accounts. So, I choice to remain the donation, the donation site is not only an income (a very small one, much less than server cost), but more importantly, it is an evidence that we are alive.

As to the code, the releasing of our code is not not related to all these financial problems. We will release codes once related documents are prepared.

**Comment by DavidsonAudioMulti** [comment]
I just wanted to say thank you for your hard work on this amazing project!! If at all possible when you release the next version can we get a no install cpu & no install gpu version? If so I would gladly pay 100 USD for it. I know open source is great "free" but this software is insanely good at coloring and worth money. The company that ripped off version 2 should get sued and the money should go to you and this project. Keep up the project I can't wait.... Give us a sign on V4 V5 and I will donate.

**Comment by SNSLogty** [comment]
> I just wanted to say thank you for your hard work on this amazing project!! If at all possible when you release the next version can we get a no install cpu & no install gpu version? If so I would gladly pay 100 USD for it. I know open source is great "free" but this software is insanely good at coloring and worth money. The company that ripped off version 2 should get sued and the money should go to you and this project. Keep up the project I can't wait.... Give us a sign on V4 V5 and I will donate.

@DavidsonAudioMulti 
Thank you :)
Don't worry about our project,we will release the offline version of v4 after the paper passed.And we won't charge for the new version.
