### ISSUE TITLE
Where can we download the supplemental material of style2paints v3?

### ISSUE THREAD

**Issue by cumtwb** [lllyasviel/style2paints#98]
The supplemental material is mentioned in the paper "Two-stage Sketch Colorization".

**Comment by Razgrits** [comment]
v4 should be releasing soon(hopefully) so it's better to just wait for that.

**Comment by gceboh** [comment]
For supplemental material mentioned in the paper  "Two-stage Sketch Colorization":
https://dl.acm.org/doi/abs/10.1145/3272127.3275090
you can find 'a261-zhang.zip' in the page.
