### ISSUE TITLE
change the output quality / resolution / compute budget / png instead of jpg ? 

### ISSUE THREAD

**Issue by Ulf3000** [lllyasviel/style2paints#99]
Hey i have v3 running fine locally with gpu support , everything worked fine after a few tries and finally installing miniconda. It auto downloads the dependencies and correct python version. 

Now i want to increase the quality as the jpg atrifacts are quite nasty and maybe a higher resolution would be nice, 

which lines must i edit , can you point me there ?

**Comment by stefnotch** [comment]
If the jpg compression artifacts are an issue, you could try to increase the `cv2.imwrite` quality by setting the last, optional parameter to 100.

So, this
```
cv2.imwrite(room_path + '/sketch.128.jpg', sketch_128)
```
would turn into
```
cv2.imwrite(room_path + '/sketch.128.jpg', sketch_128, 100)
```
That `,100` specifies that the quality should be maxed out.

Here is the file with all the calls to `cv2.imwrite`
https://github.com/lllyasviel/style2paints/blob/42ba197c2326d288c0fc038c4527ba5efea5d8e2/V3/server/server.py

**Comment by Ulf3000** [comment]
ok seems like thats not my problem as the default quality should be 95% which doesnt make heavy artifacts !

so the problem is the lowres internal processing, 

i tried to change line 52 to 1024 instead of 512 .. but then my gpu runs out of allocation somewhere , trying the cpu method now

**Comment by Xeddius** [comment]
cv2.imwrite should allow .png to be used, I'll test to see if the changes can be made as I enjoy lossless compression.
